# -*- coding: utf-8; -*-

## This file contains a list of all of biographical CVs that are
## maintained in the IMS Celebratio collection.  It can point to items
## that are stored in this Github repository, or items that are stored
## elsewhere.  The format is illustrated in this truncated sample:

# urllist = [["Aitken, Alexander C.", "http://metameso.org/~joe/aitken.tex"],
#            ["Birnbaum, Z. William", "http://metameso.org/~joe/birnbaum.tex"],
#            ["Carver, Harry C.", "tex_files/Carver%2C%20Harry%20C..tex"],
#            ["Dugué, Daniel", "tex_files/Dugu%C3%A9%2C%20Daniel.tex"]]

# The first 2 files are hosted at remote URLs, specified in full, and
# the last two files (indicated by "tex_files/URL-ENCODED-FILENAME")
# are maintained in this repository, under the direct control of IMS.

# As of September 21st 2014, only one file will be hosted remotely,
# for demonstration purposes (aitken.tex).  It is expected that IMS
# will find remote maintainers for many of the files, and replace the
# local addresses with remote URLs.

# In the nightly workflow, this file is pulled down and any remote
# addresses are polled for changes.  So it is important that this file
# be kept up to date, and in a consistent format.  In particular, the
# full names of IMS members are used as keys and should probably not
# change, except in case of marriage, or other cases where the
# person's name changes: this would also require renaming files in the
# Github repository for sake of consistency.

urllist = [["Adler, Robert J.", "tex_files/Adler%2C%20Robert%20J..tex"], 
           ["Agresti, Alan", "tex_files/Agresti%2C%20Alan.tex"], 
           ["Aitchison, John", "tex_files/Aitchison%2C%20John.tex"], 
           ["Aitken, Alexander C.", "http://metameso.org/~joe/aitken.tex"], 
           ["Akaike, Hirotugu", "tex_files/Akaike%2C%20Hirotugu.tex"], 
           ["Akritas, Michael G.", "tex_files/Akritas%2C%20Michael%20G..tex"], 
           ["Alam, Khursheed", "tex_files/Alam%2C%20Khursheed.tex"], 
           ["Albert, Arthur E.", "tex_files/Albert%2C%20Arthur%20E..tex"], 
           ["Aldous, David J.", "tex_files/Aldous%2C%20David%20J..tex"], 
           ["Alexander, Kenneth S.", "tex_files/Alexander%2C%20Kenneth%20S..tex"], 
           ["Allen, Roy G. D.", "tex_files/Allen%2C%20Roy%20G.%20D..tex"], 
           ["Allison, David B.", "tex_files/Allison%2C%20David%20B..tex"], 
           ["Amit, Yali", "tex_files/Amit%2C%20Yali.tex"], 
           ["Andersen, Erik Sparre", "tex_files/Andersen%2C%20Erik%20Sparre.tex"], 
           ["Anderson, Oskar J. V.", "tex_files/Anderson%2C%20Oskar%20J.%20V..tex"], 
           ["Anderson, Richard L.", "tex_files/Anderson%2C%20Richard%20L..tex"], 
           ["Anderson, Theodore W., Jr.", "tex_files/Anderson%2C%20Theodore%20W.%2C%20Jr..tex"], 
           ["Anscombe, Francis J.", "tex_files/Anscombe%2C%20Francis%20J..tex"], 
           ["Antoniadis, Anestis", "tex_files/Antoniadis%2C%20Anestis.tex"], 
           ["Arcones, Miguel A.", "tex_files/Arcones%2C%20Miguel%20A..tex"], 
           ["Arjas, Elja", "tex_files/Arjas%2C%20Elja.tex"], 
           ["Armitage, Peter", "tex_files/Armitage%2C%20Peter.tex"], 
           ["Arnold, Barry C.", "tex_files/Arnold%2C%20Barry%20C..tex"], 
           ["Arnold, Kenneth J.", "tex_files/Arnold%2C%20Kenneth%20J..tex"], 
           ["Arratia, Richard A.", "tex_files/Arratia%2C%20Richard%20A..tex"], 
           ["Arrow, Kenneth J.", "tex_files/Arrow%2C%20Kenneth%20J..tex"], 
           ["Asmussen, Søren", "tex_files/Asmussen%2C%20S%C3%B8ren.tex"], 
           ["Athreya, Krishna B.", "tex_files/Athreya%2C%20Krishna%20B..tex"], 
           ["Aït-Sahalia, Yacine", "tex_files/A%C3%AFt-Sahalia%2C%20Yacine.tex"], 
           ["Babu, Gutti Jogesh", "tex_files/Babu%2C%20Gutti%20Jogesh.tex"], 
           ["Bahadur, Raghu Raj", "tex_files/Bahadur%2C%20Raghu%20Raj.tex"], 
           ["Bai, Zhidong", "tex_files/Bai%21C%20Zhidong.tex"], 
           ["Bailey, Rosemary A.", "tex_files/Bailey%2C%20Rosemary%20A..tex"], 
           ["Baker, George A.", "tex_files/Baker%2C%20George%20A..tex"], 
           ["Balakrishnan, Narayanaswamy", "tex_files/Balakrishnan%2C%20Narayanaswamy.tex"], 
           ["Bancroft, Theodore A.", "tex_files/Bancroft%2C%20Theodore%20A..tex"], 
           ["Banerjee, Kali S.", "tex_files/Banerjee%2C%20Kali%20S..tex"], 
           ["Banks, David L.", "tex_files/Banks%2C%20David%20L..tex"], 
           ["Barankin, Edward W.", "tex_files/Barankin%2C%20Edward%20W..tex"], 
           ["Barbour, Andrew D.", "tex_files/Barbour%2C%20Andrew%20D..tex"], 
           ["Barlow, Martin T.", "tex_files/Barlow%2C%20Martin%20T..tex"], 
           ["Barlow, Richard E.", "tex_files/Barlow%2C%20Richard%20E..tex"], 
           ["Barnard, George A.", "tex_files/Barnard%2C%20George%20A..tex"], 
           ["Barndorff-Nielsen, O. E.", "tex_files/Barndorff-Nielsen%2C%20O.%20E..tex"], 
           ["Bartholomew, David J.", "tex_files/Bartholomew%2C%20David%20J..tex"], 
           ["Bartky, Walter S.", "tex_files/Bartky%2C%20Walter%20S..tex"], 
           ["Bartlett, Maurice S.", "tex_files/Bartlett%2C%20Maurice%20S..tex"], 
           ["Bartlett, Peter L.", "tex_files/Bartlett%2C%20Peter%20L..tex"], 
           ["Barton, David E.", "tex_files/Barton%2C%20David%20E..tex"], 
           ["Bartoszyński, Robert", "tex_files/Bartoszy%C5%84ski%2C%20Robert.tex"], 
           ["Basawa, Ishwar V.", "tex_files/Basawa%2C%20Ishwar%20V..tex"], 
           ["Bass, Richard F.", "tex_files/Bass%2C%20Richard%20F..tex"], 
           ["Basu, Asit P.", "tex_files/Basu%2C%20Asit%20P..tex"], 
           ["Basu, Debabrata", "tex_files/Basu%2C%20Debabrata.tex"], 
           ["Baten, William Dowell", "tex_files/Baten%2C%20William%20Dowell.tex"], 
           ["Bather, John A.", "tex_files/Bather%2C%20John%20A..tex"], 
           ["Baxendale, Peter H.", "tex_files/Baxendale%2C%20Peter%20H..tex"], 
           ["Baxter, Glen E.", "tex_files/Baxter%2C%20Glen%20E..tex"], 
           ["Bayarri, M. J. (Susie)", "tex_files/Bayarri%2C%20M.%20J.%20%28Susie%29.tex"], 
           ["Bañuelos, Rodrigo", "tex_files/Ba%C3%B1uelos%2C%20Rodrigo.tex"], 
           ["Bechhofer, Robert E.", "tex_files/Bechhofer%2C%20Robert%20E..tex"], 
           ["Bell, Charles B., Jr.", "tex_files/Bell%2C%20Charles%20B.%2C%20Jr..tex"], 
           ["Belyaev, Yuri K.", "tex_files/Belyaev%2C%20Yuri%20K..tex"], 
           ["Ben Arous, Gérard", "tex_files/Ben%20Arous%2C%20G%C3%A9rard.tex"], 
           ["Beran, Rudolf J.", "tex_files/Beran%2C%20Rudolf%20J..tex"], 
           ["Berger, James O.", "tex_files/Berger%2C%20James%20O..tex"], 
           ["Berger, Roger L.", "tex_files/Berger%2C%20Roger%20L..tex"], 
           ["Bergström, Harald", "tex_files/Bergstr%C3%B6m%2C%20Harald.tex"], 
           ["Berk, Robert H.", "tex_files/Berk%2C%20Robert%20H..tex"], 
           ["Berkson, Joseph", "tex_files/Berkson%2C%20Joseph.tex"], 
           ["Berliner, L. Mark", "tex_files/Berliner%2C%20L.%20Mark.tex"], 
           ["Berman, Simeon M.", "tex_files/Berman%2C%20Simeon%20M..tex"], 
           ["Berry, Donald A.", "tex_files/Berry%2C%20Donald%20A..tex"], 
           ["Besag, Julian E.", "tex_files/Besag%2C%20Julian%20E..tex"], 
           ["Bhansali, R. J.", "tex_files/Bhansali%2C%20R.%20J..tex"], 
           ["Bhattacharya, P. K.", "tex_files/Bhattacharya%2C%20P.%20K..tex"], 
           ["Bhattacharya, Rabindra N.", "tex_files/Bhattacharya%2C%20Rabindra%20N..tex"], 
           ["Bhattacharyya, Gouri K.", "tex_files/Bhattacharyya%2C%20Gouri%20K..tex"], 
           ["Bickel, Peter J.", "tex_files/Bickel%2C%20Peter%20J..tex"], 
           ["Billard, Lynne", "tex_files/Billard%2C%20Lynne.tex"], 
           ["Billingsley, Patrick P.", "tex_files/Billingsley%2C%20Patrick%20P..tex"], 
           ["Bingham, Christopher", "tex_files/Bingham%2C%20Christopher.tex"], 
           ["Birgé, Lucien", "tex_files/Birg%C3%A9%2C%20Lucien.tex"], 
           ["Birnbaum, Allan", "tex_files/Birnbaum%2C%20Allan.tex"], 
           ["Birnbaum, Z. William", "tex_files/Birnbaum%2C%20Z.%20William.tex"], 
           ["Blackwell, David H.", "tex_files/Blackwell%2C%20David%20H..tex"], 
           ["Bliss, Chester I.", "tex_files/Bliss%2C%20Chester%20I..tex"], 
           ["Block, Henry W.", "tex_files/Block%2C%20Henry%20W..tex"], 
           ["Blom, Gunnar", "tex_files/Blom%2C%20Gunnar.tex"], 
           ["Bloomfield, Peter", "tex_files/Bloomfield%2C%20Peter.tex"], 
           ["Blum, Julius R.", "tex_files/Blum%2C%20Julius%20R..tex"], 
           ["Blumenthal, Robert M.", "tex_files/Blumenthal%2C%20Robert%20M..tex"], 
           ["Blumenthal, Saul", "tex_files/Blumenthal%2C%20Saul.tex"], 
           ["Blyth, Colin R.", "tex_files/Blyth%2C%20Colin%20R..tex"], 
           ["Bock, Mary Ellen", "tex_files/Bock%2C%20Mary%20Ellen.tex"], 
           ["Boente, Graciela L. Boente", "tex_files/Boente%2C%20Graciela%20L.%20Boente.tex"], 
           ["Bolthausen, Erwin", "tex_files/Bolthausen%2C%20Erwin.tex"], 
           ["Bookstein, Fred L.", "tex_files/Bookstein%2C%20Fred%20L..tex"], 
           ["Bose, Arup", "tex_files/Bose%2C%20Arup.tex"], 
           ["Bose, Raj Chandra", "tex_files/Bose%2C%20Raj%20Chandra.tex"], 
           ["Bovier, Anton", "tex_files/Bovier%2C%20Anton.tex"], 
           ["Bowker, Albert H.", "tex_files/Bowker%2C%20Albert%20H..tex"], 
           ["Bowman, Kimiko O.", "tex_files/Bowman%2C%20Kimiko%20O..tex"], 
           ["Box, George E. P.", "tex_files/Box%2C%20George%20E.%20P..tex"], 
           ["Bradley, Ralph A.", "tex_files/Bradley%2C%20Ralph%20A..tex"], 
           ["Bradley, Richard C.", "tex_files/Bradley%2C%20Richard%20C..tex"], 
           ["Bramson, Maury", "tex_files/Bramson%2C%20Maury.tex"], 
           ["Breiman, Leo", "tex_files/Breiman%2C%20Leo.tex"], 
           ["Brillinger, David R.", "tex_files/Brillinger%2C%20David%20R..tex"], 
           ["Brockett, Patrick L.", "tex_files/Brockett%2C%20Patrick%20L..tex"], 
           ["Brockwell, Peter J.", "tex_files/Brockwell%2C%20Peter%20J..tex"], 
           ["Brown, Bruce M.", "tex_files/Brown%2C%20Bruce%20M..tex"], 
           ["Brown, George W.", "tex_files/Brown%2C%20George%20W..tex"], 
           ["Brown, Lawrence D.", "tex_files/Brown%2C%20Lawrence%20D..tex"], 
           ["Brown, Mark", "tex_files/Brown%2C%20Mark.tex"], 
           ["Brown, Philip J.", "tex_files/Brown%2C%20Philip%20J..tex"], 
           ["Brunk, Hugh D.", "tex_files/Brunk%2C%20Hugh%20D..tex"], 
           ["Bruss, Franz Thomas", "tex_files/Bruss%2C%20Franz%20Thomas.tex"], 
           ["Budhiraja, Amarjit S.", "tex_files/Budhiraja%2C%20Amarjit%20S..tex"], 
           ["Buehler, Robert J.", "tex_files/Buehler%2C%20Robert%20J..tex"], 
           ["Buja, Andreas", "tex_files/Buja%2C%20Andreas.tex"], 
           ["Burdzy, Krzysztof", "tex_files/Burdzy%2C%20Krzysztof.tex"], 
           ["Burkholder, Donald L.", "tex_files/Burkholder%2C%20Donald%20L..tex"], 
           ["Burr, Irving W.", "tex_files/Burr%2C%20Irving%20W..tex"], 
           ["Bühler, Wolfgang J.", "tex_files/B%C3%BChler%2C%20Wolfgang%20J..tex"], 
           ["Bühlmann, Peter L.", "tex_files/B%C3%BChlmann%2C%20Peter%20L..tex"], 
           ["Cacoullos, Theophilos", "tex_files/Cacoullos%2C%20Theophilos.tex"], 
           ["Cai, Jianwen", "tex_files/Cai%2C%20Jianwen.tex"], 
           ["Cai, T. Tony", "tex_files/Cai%2C%20T.%20Tony.tex"], 
           ["Cambanis, Stamatis", "tex_files/Cambanis%2C%20Stamatis.tex"], 
           ["Camp, Burton H.", "tex_files/Camp%2C%20Burton%20H..tex"], 
           ["Carmona, Rene A.", "tex_files/Carmona%2C%20Rene%20A..tex"], 
           ["Carriquiry, Alicia L.", "tex_files/Carriquiry%2C%20Alicia%20L..tex"], 
           ["Carroll, Raymond J.", "tex_files/Carroll%2C%20Raymond%20J..tex"], 
           ["Carver, Harry C.", "tex_files/Carver%2C%20Harry%20C..tex"], 
           ["Casella, George C.", "tex_files/Casella%2C%20George%20C..tex"], 
           ["Chakravarti, Indra M.", "tex_files/Chakravarti%2C%20Indra%20M..tex"], 
           ["Chambers, John M.", "tex_files/Chambers%2C%20John%20M..tex"], 
           ["Chan, Kung-Sik", "tex_files/Chan%2C%20Kung-Sik.tex"], 
           ["Chan, Lai K.", "tex_files/Chan%2C%20Lai%20K..tex"], 
           ["Chan, Ngai Hang", "tex_files/Chan%2C%20Ngai%20Hang.tex"], 
           ["Chang, Theodore C.", "tex_files/Chang%2C%20Theodore%20C..tex"], 
           ["Chao, Anne", "tex_files/Chao%2C%20Anne.tex"], 
           ["Chao, Min-Te", "tex_files/Chao%2C%20Min-Te.tex"], 
           ["Chapman, Douglas G.", "tex_files/Chapman%2C%20Douglas%20G..tex"], 
           ["Chaudhuri, Probal", "tex_files/Chaudhuri%2C%20Probal.tex"], 
           ["Chen, Jiahua", "tex_files/Chen%2C%20Jiahua.tex"], 
           ["Chen, Kani", "tex_files/Chen%2C%20Kani.tex"], 
           ["Chen, Louis H. Y.", "tex_files/Chen%2C%20Louis%20H.%20Y..tex"], 
           ["Chen, Ming-Hui", "tex_files/Chen%2C%20Ming-Hui.tex"], 
           ["Chen, Rong", "tex_files/Chen%2C%20Rong.tex"], 
           ["Chen, Song Xi", "tex_files/Chen%2C%20Song%20Xi.tex"], 
           ["Chen, Xia", "tex_files/Chen%2C%20Xia.tex"], 
           ["Chen, Xiru", "tex_files/Chen%2C%20Xiru.tex"], 
           ["Chen, Zhen-Qing", "tex_files/Chen%2C%20Zhen-Qing.tex"], 
           ["Cheng, Ching-Shui", "tex_files/Cheng%2C%20Ching-Shui.tex"], 
           ["Cheng, Ming-Yen", "tex_files/Cheng%2C%20Ming-Yen.tex"], 
           ["Chernoff, Herman", "tex_files/Chernoff%2C%20Herman.tex"], 
           ["Chiang, Chin Long", "tex_files/Chiang%2C%20Chin%20Long.tex"], 
           ["Chow, Yuan S.", "tex_files/Chow%2C%20Yuan%20S..tex"], 
           ["Christensen, Ronald", "tex_files/Christensen%2C%20Ronald.tex"], 
           ["Chung, Kai-Lai", "tex_files/Chung%2C%20Kai-Lai.tex"], 
           ["Claeskens, Gerda", "tex_files/Claeskens%2C%20Gerda.tex"], 
           ["Cleveland, William S., II", "tex_files/Cleveland%2C%20William%20S.%2C%20II.tex"], 
           ["Clifford, Peter", "tex_files/Clifford%2C%20Peter.tex"], 
           ["Cochran, William G.", "tex_files/Cochran%2C%20William%20G..tex"], 
           ["Cohen, Arthur", "tex_files/Cohen%2C%20Arthur.tex"], 
           ["Cohn, Harry", "tex_files/Cohn%2C%20Harry.tex"], 
           ["Cook, R. Dennis", "tex_files/Cook%2C%20R.%20Dennis.tex"], 
           ["Copeland, Arthur H.", "tex_files/Copeland%2C%20Arthur%20H..tex"], 
           ["Cornfield, Jerome", "tex_files/Cornfield%2C%20Jerome.tex"], 
           ["Cover, Thomas M.", "tex_files/Cover%2C%20Thomas%20M..tex"], 
           ["Cox, David R.", "tex_files/Cox%2C%20David%20R..tex"], 
           ["Cox, Gertrude M.", "tex_files/Cox%2C%20Gertrude%20M..tex"], 
           ["Cox, J. Theodore", "tex_files/Cox%2C%20J.%20Theodore.tex"], 
           ["Craig, Allen T.", "tex_files/Craig%2C%20Allen%20T..tex"], 
           ["Craig, Cecil C.", "tex_files/Craig%2C%20Cecil%20C..tex"], 
           ["Cramér, Harald", "tex_files/Cram%C3%A9r%2C%20Harald.tex"], 
           ["Crathorne, Arthur R.", "tex_files/Crathorne%2C%20Arthur%20R..tex"], 
           ["Cressie, Noel A. C.", "tex_files/Cressie%2C%20Noel%20A.%20C..tex"], 
           ["Csörgő, Miklós", "tex_files/Cs%C3%B6rg%C5%91%2C%20Mikl%C3%B3s.tex"], 
           ["Csörgő, Sándor", "tex_files/Cs%C3%B6rg%C5%91%2C%20S%C3%A1ndor.tex"], 
           ["Curtiss, John H.", "tex_files/Curtiss%2C%20John%20H..tex"], 
           ["Cuzick, Jack", "tex_files/Cuzick%2C%20Jack.tex"], 
           ["Dabrowska, Dorota M.", "tex_files/Dabrowska%2C%20Dorota%20M..tex"], 
           ["Dahlhaus, Rainer", "tex_files/Dahlhaus%2C%20Rainer.tex"], 
           ["Dai, J. G. Jim", "tex_files/Dai%2C%20J.%20G.%20Jim.tex"], 
           ["Dalenius, Tore", "tex_files/Dalenius%2C%20Tore.tex"], 
           ["Daley, Daryl J.", "tex_files/Daley%2C%20Daryl%20J..tex"], 
           ["Daly, Joseph F.", "tex_files/Daly%2C%20Joseph%20F..tex"], 
           ["Daniel, Cuthbert", "tex_files/Daniel%2C%20Cuthbert.tex"], 
           ["Daniels, Henry E.", "tex_files/Daniels%2C%20Henry%20E..tex"], 
           ["Dantzig, George B.", "tex_files/Dantzig%2C%20George%20B..tex"], 
           ["Darling, Donald A.", "tex_files/Darling%2C%20Donald%20A..tex"], 
           ["Darmois, Georges", "tex_files/Darmois%2C%20Georges.tex"], 
           ["Das Gupta, Somesh", "tex_files/Das%20Gupta%2C%20Somesh.tex"], 
           ["DasGupta, Anirban", "tex_files/DasGupta%2C%20Anirban.tex"], 
           ["Datta, Gauri S.", "tex_files/Datta%2C%20Gauri%20S..tex"], 
           ["Datta, Somnath", "tex_files/Datta%2C%20Somnath.tex"], 
           ["David, Florence N.", "tex_files/David%2C%20Florence%20N..tex"], 
           ["David, Herbert T.", "tex_files/David%2C%20Herbert%20T..tex"], 
           ["Davidian, Marie", "tex_files/Davidian%2C%20Marie.tex"], 
           ["Davis, Burgess J.", "tex_files/Davis%2C%20Burgess%20J..tex"], 
           ["Davis, Mark H. A.", "tex_files/Davis%2C%20Mark%20H.%20A..tex"], 
           ["Davis, Richard A.", "tex_files/Davis%2C%20Richard%20A..tex"], 
           ["Davison, Anthony C.", "tex_files/Davison%2C%20Anthony%20C..tex"], 
           ["Dawid, A. Philip", "tex_files/Dawid%2C%20A.%20Philip.tex"], 
           ["Dawson, Donald A.", "tex_files/Dawson%2C%20Donald%20A..tex"], 
           ["DeGroot, Morris H.", "tex_files/DeGroot%2C%20Morris%20H..tex"], 
           ["Dean, Angela M.", "tex_files/Dean%2C%20Angela%20M..tex"], 
           ["Deheuvels, Paul", "tex_files/Deheuvels%2C%20Paul.tex"], 
           ["Delaigle, Aurore", "tex_files/Delaigle%2C%20Aurore.tex"], 
           ["Delbaen, Freddy", "tex_files/Delbaen%2C%20Freddy.tex"], 
           ["Dembo, Amir", "tex_files/Dembo%2C%20Amir.tex"], 
           ["Deming, W. Edwards", "tex_files/Deming%2C%20W.%20Edwards.tex"], 
           ["Dempster, Arthur P.", "tex_files/Dempster%2C%20Arthur%20P..tex"], 
           ["Derman, Cyrus", "tex_files/Derman%2C%20Cyrus.tex"], 
           ["Deshpande, Jayant V.", "tex_files/Deshpande%2C%20Jayant%20V..tex"], 
           ["Dette, Holger", "tex_files/Dette%2C%20Holger.tex"], 
           ["Dey, Dipak K.", "tex_files/Dey%2C%20Dipak%20K..tex"], 
           ["DiCiccio, Thomas J.", "tex_files/DiCiccio%2C%20Thomas%20J..tex"], 
           ["Diaconis, Persi W.", "tex_files/Diaconis%2C%20Persi%20W..tex"], 
           ["Dickey, James M.", "tex_files/Dickey%2C%20James%20M..tex"], 
           ["Dieulefait, Carlos E.", "tex_files/Dieulefait%2C%20Carlos%20E..tex"], 
           ["Dixon, Wilfrid J.", "tex_files/Dixon%2C%20Wilfrid%20J..tex"], 
           ["Dodd, Edward L.", "tex_files/Dodd%2C%20Edward%20L..tex"], 
           ["Dodge, Harold F.", "tex_files/Dodge%2C%20Harold%20F..tex"], 
           ["Doksum, Kjell A.", "tex_files/Doksum%2C%20Kjell%20A..tex"], 
           ["Doney, Ronald A.", "tex_files/Doney%2C%20Ronald%20A..tex"], 
           ["Donnelly, Peter J.", "tex_files/Donnelly%2C%20Peter%20J..tex"], 
           ["Donoho, David L.", "tex_files/Donoho%2C%20David%20L..tex"], 
           ["Donoho, Miriam Gasko", "tex_files/Donoho%2C%20Miriam%20Gasko.tex"], 
           ["Doob, Joseph L.", "tex_files/Doob%2C%20Joseph%20L..tex"], 
           ["Doss, Hani", "tex_files/Doss%2C%20Hani.tex"], 
           ["Draper, David", "tex_files/Draper%2C%20David.tex"], 
           ["Draper, Norman R.", "tex_files/Draper%2C%20Norman%20R..tex"], 
           ["Dryden, Ian L.", "tex_files/Dryden%2C%20Ian%20L..tex"], 
           ["DuMouchel, William", "tex_files/DuMouchel%2C%20William.tex"], 
           ["Duan, Naihua", "tex_files/Duan%2C%20Naihua.tex"], 
           ["Dubins, Lester E.", "tex_files/Dubins%2C%20Lester%20E..tex"], 
           ["Dudewicz, Edward J.", "tex_files/Dudewicz%2C%20Edward%20J..tex"], 
           ["Dudley, Richard M.", "tex_files/Dudley%2C%20Richard%20M..tex"], 
           ["Dugué, Daniel", "tex_files/Dugu%C3%A9%2C%20Daniel.tex"], 
           ["Duncan, Acheson J.", "tex_files/Duncan%2C%20Acheson%20J..tex"], 
           ["Duncan, David B.", "tex_files/Duncan%2C%20David%20B..tex"], 
           ["Dunson, David B.", "tex_files/Dunson%2C%20David%20B..tex"], 
           ["Dupač, Václav", "tex_files/Dupa%C4%8D%2C%20V%C3%A1clav.tex"], 
           ["Dupuis, Paul", "tex_files/Dupuis%2C%20Paul.tex"], 
           ["Durbin, James", "tex_files/Durbin%2C%20James.tex"], 
           ["Durrett, Richard T.", "tex_files/Durrett%2C%20Richard%20T..tex"], 
           ["Dvoretzky, Aryeh", "tex_files/Dvoretzky%2C%20Aryeh.tex"], 
           ["Dwass, Meyer", "tex_files/Dwass%2C%20Meyer.tex"], 
           ["Dwyer, Paul S.", "tex_files/Dwyer%2C%20Paul%20S..tex"], 
           ["Dykstra, Richard L.", "tex_files/Dykstra%2C%20Richard%20L..tex"], 
           ["Dynkin, Eugene B.", "tex_files/Dynkin%2C%20Eugene%20B..tex"], 
           ["Eagleson, Geoffrey K.", "tex_files/Eagleson%2C%20Geoffrey%20K..tex"], 
           ["Eaton, Morris L.", "tex_files/Eaton%2C%20Morris%20L..tex"], 
           ["Eddy, William F.", "tex_files/Eddy%2C%20William%20F..tex"], 
           ["Efromovich, Sam", "tex_files/Efromovich%2C%20Sam.tex"], 
           ["Efron, Bradley", "tex_files/Efron%2C%20Bradley.tex"], 
           ["Einmahl, John H. J.", "tex_files/Einmahl%2C%20John%20H.%20J..tex"], 
           ["Einmahl, Uwe", "tex_files/Einmahl%2C%20Uwe.tex"], 
           ["Eisenhart, Churchill", "tex_files/Eisenhart%2C%20Churchill.tex"], 
           ["Elashoff, Robert M.", "tex_files/Elashoff%2C%20Robert%20M..tex"], 
           ["Elfving, Erik Gustav", "tex_files/Elfving%2C%20Erik%20Gustav.tex"], 
           ["Ellis, Richard S.", "tex_files/Ellis%2C%20Richard%20S..tex"], 
           ["Elston, Robert C.", "tex_files/Elston%2C%20Robert%20C..tex"], 
           ["Embrechts, Paul", "tex_files/Embrechts%2C%20Paul.tex"], 
           ["Epstein, Benjamin", "tex_files/Epstein%2C%20Benjamin.tex"], 
           ["Esary, James D.", "tex_files/Esary%2C%20James%20D..tex"], 
           ["Esseen, Carl-Gustav", "tex_files/Esseen%2C%20Carl-Gustav.tex"], 
           ["Ethier, Stewart N.", "tex_files/Ethier%2C%20Stewart%20N..tex"], 
           ["Eubank, Randall L.", "tex_files/Eubank%2C%20Randall%20L..tex"], 
           ["Evans, Steven N.", "tex_files/Evans%2C%20Steven%20N..tex"], 
           ["Fabian, Václav", "tex_files/Fabian%2C%20V%C3%A1clav.tex"], 
           ["Fan, Jianqing", "tex_files/Fan%2C%20Jianqing.tex"], 
           ["Fang, Kai-Tai", "tex_files/Fang%2C%20Kai-Tai.tex"], 
           ["Farrell, Roger H.", "tex_files/Farrell%2C%20Roger%20H..tex"], 
           ["Federer, Walter T.", "tex_files/Federer%2C%20Walter%20T..tex"], 
           ["Feigin, Paul D.", "tex_files/Feigin%2C%20Paul%20D..tex"], 
           ["Feller, William", "tex_files/Feller%2C%20William.tex"], 
           ["Ferguson, Thomas S.", "tex_files/Ferguson%2C%20Thomas%20S..tex"], 
           ["Ferrari, Pablo A.", "tex_files/Ferrari%2C%20Pablo%20A..tex"], 
           ["Feuerverger, Andrey", "tex_files/Feuerverger%2C%20Andrey.tex"], 
           ["Fienberg, Stephen E.", "tex_files/Fienberg%2C%20Stephen%20E..tex"], 
           ["Fill, James A.", "tex_files/Fill%2C%20James%20A..tex"], 
           ["Finney, David J.", "tex_files/Finney%2C%20David%20J..tex"], 
           ["Fishburn, Peter C.", "tex_files/Fishburn%2C%20Peter%20C..tex"], 
           ["Fisher, Irving", "tex_files/Fisher%2C%20Irving.tex"], 
           ["Fisher, Lloyd D.", "tex_files/Fisher%2C%20Lloyd%20D..tex"], 
           ["Fisz, Marek", "tex_files/Fisz%2C%20Marek.tex"], 
           ["Fitzsimmons, Patrick J.", "tex_files/Fitzsimmons%2C%20Patrick%20J..tex"], 
           ["Fix, Evelyn", "tex_files/Fix%2C%20Evelyn.tex"], 
           ["Flournoy, Nancy", "tex_files/Flournoy%2C%20Nancy.tex"], 
           ["Fortet, Robert", "tex_files/Fortet%2C%20Robert.tex"], 
           ["Foster, Dean P.", "tex_files/Foster%2C%20Dean%20P..tex"], 
           ["Fouque, Jean-Pierre", "tex_files/Fouque%2C%20Jean-Pierre.tex"], 
           ["Fox, Martin", "tex_files/Fox%2C%20Martin.tex"], 
           ["Fraser, Donald A. S.", "tex_files/Fraser%2C%20Donald%20A.%20S..tex"], 
           ["Freedman, David A.", "tex_files/Freedman%2C%20David%20A..tex"], 
           ["Friedman, Milton", "tex_files/Friedman%2C%20Milton.tex"], 
           ["Frisch, Ragnar A. K.", "tex_files/Frisch%2C%20Ragnar%20A.%20K..tex"], 
           ["Fristedt, Bert", "tex_files/Fristedt%2C%20Bert.tex"], 
           ["Fry, Thornton C.", "tex_files/Fry%2C%20Thornton%20C..tex"], 
           ["Fu, James C.", "tex_files/Fu%2C%20James%20C..tex"], 
           ["Fujikoshi, Yasunori", "tex_files/Fujikoshi%2C%20Yasunori.tex"], 
           ["Fuller, Wayne A.", "tex_files/Fuller%2C%20Wayne%20A..tex"], 
           ["Fung, Wing-Kam", "tex_files/Fung%2C%20Wing-Kam.tex"], 
           ["Föllmer, Hans", "tex_files/F%C3%B6llmer%2C%20Hans.tex"], 
           ["Gabriel, K. Ruben", "tex_files/Gabriel%2C%20K.%20Ruben.tex"], 
           ["Galambos, János", "tex_files/Galambos%2C%20J%C3%A1nos.tex"], 
           ["Gani, Joseph M.", "tex_files/Gani%2C%20Joseph%20M..tex"], 
           ["Gart, John J.", "tex_files/Gart%2C%20John%20J..tex"], 
           ["Gastwirth, Joseph L.", "tex_files/Gastwirth%2C%20Joseph%20L..tex"], 
           ["Gaver, Donald P., Jr.", "tex_files/Gaver%2C%20Donald%20P.%2C%20Jr..tex"], 
           ["Geary, Robert C.", "tex_files/Geary%2C%20Robert%20C..tex"], 
           ["Geiringer, Hilda", "tex_files/Geiringer%2C%20Hilda.tex"], 
           ["Geisser, Seymour", "tex_files/Geisser%2C%20Seymour.tex"], 
           ["Gelfand, Alan E.", "tex_files/Gelfand%2C%20Alan%20E..tex"], 
           ["Gelman, Andrew", "tex_files/Gelman%2C%20Andrew.tex"], 
           ["Geman, Donald J.", "tex_files/Geman%2C%20Donald%20J..tex"], 
           ["Geman, Stuart A.", "tex_files/Geman%2C%20Stuart%20A..tex"], 
           ["Genest, Christian", "tex_files/Genest%2C%20Christian.tex"], 
           ["Genovese, Christopher R.", "tex_files/Genovese%2C%20Christopher%20R..tex"], 
           ["Genton, Marc G.", "tex_files/Genton%2C%20Marc%20G..tex"], 
           ["George, Edward I.", "tex_files/George%2C%20Edward%20I..tex"], 
           ["Getoor, Ronald K.", "tex_files/Getoor%2C%20Ronald%20K..tex"], 
           ["Ghosal, Subhashis", "tex_files/Ghosal%2C%20Subhashis.tex"], 
           ["Ghosh, Bhaskar K.", "tex_files/Ghosh%2C%20Bhaskar%20K..tex"], 
           ["Ghosh, Jayanta K.", "tex_files/Ghosh%2C%20Jayanta%20K..tex"], 
           ["Ghosh, Malay", "tex_files/Ghosh%2C%20Malay.tex"], 
           ["Ghurye, Sudhish G.", "tex_files/Ghurye%2C%20Sudhish%20G..tex"], 
           ["Gidas, Basilis", "tex_files/Gidas%2C%20Basilis.tex"], 
           ["Gijbels, Irène", "tex_files/Gijbels%2C%20Ir%C3%A8ne.tex"], 
           ["Gilford, Dorothy M.", "tex_files/Gilford%2C%20Dorothy%20M..tex"], 
           ["Gill, Richard D.", "tex_files/Gill%2C%20Richard%20D..tex"], 
           ["Giné-Masdéu, Evarist", "tex_files/Gin%C3%A9-Masd%C3%A9u%2C%20Evarist.tex"], 
           ["Giri, Narayan Chandra", "tex_files/Giri%2C%20Narayan%20Chandra.tex"], 
           ["Girshick, Meyer A.", "tex_files/Girshick%2C%20Meyer%20A..tex"], 
           ["Glaz, Joseph", "tex_files/Glaz%2C%20Joseph.tex"], 
           ["Gleser, Leon J.", "tex_files/Gleser%2C%20Leon%20J..tex"], 
           ["Glynn, Peter W.", "tex_files/Glynn%2C%20Peter%20W..tex"], 
           ["Gnanadesikan, Ramanathan", "tex_files/Gnanadesikan%2C%20Ramanathan.tex"], 
           ["Gnedenko, Boris V.", "tex_files/Gnedenko%2C%20Boris%20V..tex"], 
           ["Gneiting, Tilmann", "tex_files/Gneiting%2C%20Tilmann.tex"], 
           ["Godambe, Vidyadhar P.", "tex_files/Godambe%2C%20Vidyadhar%20P..tex"], 
           ["Goel, Prem K.", "tex_files/Goel%2C%20Prem%20K..tex"], 
           ["Goldstein, Larry", "tex_files/Goldstein%2C%20Larry.tex"], 
           ["Good, Irving J.", "tex_files/Good%2C%20Irving%20J..tex"], 
           ["Goodman, Leo A.", "tex_files/Goodman%2C%20Leo%20A..tex"], 
           ["Goodman, Victor W.", "tex_files/Goodman%2C%20Victor%20W..tex"], 
           ["Gordon, Louis", "tex_files/Gordon%2C%20Louis.tex"], 
           ["Gorostiza, Luis G.", "tex_files/Gorostiza%2C%20Luis%20G..tex"], 
           ["Govindarajulu, Z.", "tex_files/Govindarajulu%2C%20Z..tex"], 
           ["Gray, Lawrence F.", "tex_files/Gray%2C%20Lawrence%20F..tex"], 
           ["Gray, Robert M.", "tex_files/Gray%2C%20Robert%20M..tex"], 
           ["Graybill, Franklin A.", "tex_files/Graybill%2C%20Franklin%20A..tex"], 
           ["Green, Peter J.", "tex_files/Green%2C%20Peter%20J..tex"], 
           ["Greenberg, Bernard G.", "tex_files/Greenberg%2C%20Bernard%20G..tex"], 
           ["Greenhouse, Samuel W.", "tex_files/Greenhouse%2C%20Samuel%20W..tex"], 
           ["Greenwood, Priscilla E.", "tex_files/Greenwood%2C%20Priscilla%20E..tex"], 
           ["Grenander, Ulf", "tex_files/Grenander%2C%20Ulf.tex"], 
           ["Griffeath, David", "tex_files/Griffeath%2C%20David.tex"], 
           ["Griffiths, Robert C.", "tex_files/Griffiths%2C%20Robert%20C..tex"], 
           ["Grimmett, Geoffrey R.", "tex_files/Grimmett%2C%20Geoffrey%20R..tex"], 
           ["Groeneboom, Piet", "tex_files/Groeneboom%2C%20Piet.tex"], 
           ["Grubbs, Frank E.", "tex_files/Grubbs%2C%20Frank%20E..tex"], 
           ["Gumbel, Emil J.", "tex_files/Gumbel%2C%20Emil%20J..tex"], 
           ["Gundy, Richard F.", "tex_files/Gundy%2C%20Richard%20F..tex"], 
           ["Gupta, Shanti S.", "tex_files/Gupta%2C%20Shanti%20S..tex"], 
           ["Gurland, John", "tex_files/Gurland%2C%20John.tex"], 
           ["Gut, Allan", "tex_files/Gut%2C%20Allan.tex"], 
           ["Guttman, Irwin", "tex_files/Guttman%2C%20Irwin.tex"], 
           ["Guttman, Louis", "tex_files/Guttman%2C%20Louis.tex"], 
           ["Gänßler, Peter E.", "tex_files/G%C3%A4n%C3%9Fler%2C%20Peter%20E..tex"], 
           ["Götze, Friedrich", "tex_files/G%C3%B6tze%2C%20Friedrich.tex"], 
           ["Haavelmo, Trygve M.", "tex_files/Haavelmo%2C%20Trygve%20M..tex"], 
           ["Haberman, Shelby J.", "tex_files/Haberman%2C%20Shelby%20J..tex"], 
           ["Hahn, Marjorie G.", "tex_files/Hahn%2C%20Marjorie%20G..tex"], 
           ["Hald, Anders H.", "tex_files/Hald%2C%20Anders%20H..tex"], 
           ["Hall, Peter G.", "tex_files/Hall%2C%20Peter%20G..tex"], 
           ["Hall, W. Jackson", "tex_files/Hall%2C%20W.%20Jackson.tex"], 
           ["Hallin, Marc", "tex_files/Hallin%2C%20Marc.tex"], 
           ["Halperin, Max", "tex_files/Halperin%2C%20Max.tex"], 
           ["Hammersley, John Michael", "tex_files/Hammersley%2C%20John%20Michael.tex"], 
           ["Hannan, James F.", "tex_files/Hannan%2C%20James%20F..tex"], 
           ["Hansen, Morris H.", "tex_files/Hansen%2C%20Morris%20H..tex"], 
           ["Hanson, David L.", "tex_files/Hanson%2C%20David%20L..tex"], 
           ["Harkness, William L.", "tex_files/Harkness%2C%20William%20L..tex"], 
           ["Harrington, David P.", "tex_files/Harrington%2C%20David%20P..tex"], 
           ["Harris, Bernard", "tex_files/Harris%2C%20Bernard.tex"], 
           ["Harris, Theodore E.", "tex_files/Harris%2C%20Theodore%20E..tex"], 
           ["Harrison, J. Michael", "tex_files/Harrison%2C%20J.%20Michael.tex"], 
           ["Harshbarger, Boyd", "tex_files/Harshbarger%2C%20Boyd.tex"], 
           ["Hart, Jeffrey D.", "tex_files/Hart%2C%20Jeffrey%20D..tex"], 
           ["Harter, H. Leon", "tex_files/Harter%2C%20H.%20Leon.tex"], 
           ["Hartigan, John A.", "tex_files/Hartigan%2C%20John%20A..tex"], 
           ["Hartley, Herman Otto", "tex_files/Hartley%2C%20Herman%20Otto.tex"], 
           ["Harville, David A.", "tex_files/Harville%2C%20David%20A..tex"], 
           ["Hastie, Trevor J.", "tex_files/Hastie%2C%20Trevor%20J..tex"], 
           ["He, Xuming", "tex_files/He%2C%20Xuming.tex"], 
           ["Heathcote, Christopher R.", "tex_files/Heathcote%2C%20Christopher%20R..tex"], 
           ["Heckman, Nancy E.", "tex_files/Heckman%2C%20Nancy%20E..tex"], 
           ["Hedayat, A. Samad", "tex_files/Hedayat%2C%20A.%20Samad.tex"], 
           ["Heitjan, Daniel F.", "tex_files/Heitjan%2C%20Daniel%20F..tex"], 
           ["Hemelrijk, Jan", "tex_files/Hemelrijk%2C%20Jan.tex"], 
           ["Henderson, Robert", "tex_files/Henderson%2C%20Robert.tex"], 
           ["Herzberg, Agnes M.", "tex_files/Herzberg%2C%20Agnes%20M..tex"], 
           ["Hettmansperger, Thomas P.", "tex_files/Hettmansperger%2C%20Thomas%20P..tex"], 
           ["Heyde, Christopher C.", "tex_files/Heyde%2C%20Christopher%20C..tex"], 
           ["Hickernell, Fred J.", "tex_files/Hickernell%2C%20Fred%20J..tex"], 
           ["Hildreth, Clifford G.", "tex_files/Hildreth%2C%20Clifford%20G..tex"], 
           ["Hill, Bruce M.", "tex_files/Hill%2C%20Bruce%20M..tex"], 
           ["Hill, Theodore P.", "tex_files/Hill%2C%20Theodore%20P..tex"], 
           ["Hinich, Melvin J.", "tex_files/Hinich%2C%20Melvin%20J..tex"], 
           ["Hinkley, David V.", "tex_files/Hinkley%2C%20David%20V..tex"], 
           ["Hobert, James P.", "tex_files/Hobert%2C%20James%20P..tex"], 
           ["Hodges, Joseph L., Jr.", "tex_files/Hodges%2C%20Joseph%20L.%2C%20Jr..tex"], 
           ["Hoeffding, Wassily", "tex_files/Hoeffding%2C%20Wassily.tex"], 
           ["Hoel, Paul G.", "tex_files/Hoel%2C%20Paul%20G..tex"], 
           ["Hogg, Robert V.", "tex_files/Hogg%2C%20Robert%20V..tex"], 
           ["Holland, Paul W.", "tex_files/Holland%2C%20Paul%20W..tex"], 
           ["Hollander, Myles", "tex_files/Hollander%2C%20Myles.tex"], 
           ["Holley, Richard A.", "tex_files/Holley%2C%20Richard%20A..tex"], 
           ["Holmes, Susan", "tex_files/Holmes%2C%20Susan.tex"], 
           ["Hoppe, Fred M.", "tex_files/Hoppe%2C%20Fred%20M..tex"], 
           ["Horst, A. Paul", "tex_files/Horst%2C%20A.%20Paul.tex"], 
           ["Horváth, Lajos", "tex_files/Horv%C3%A1th%2C%20Lajos.tex"], 
           ["Hosoya, Yuzo", "tex_files/Hosoya%2C%20Yuzo.tex"], 
           ["Hotelling, Harold", "tex_files/Hotelling%2C%20Harold.tex"], 
           ["Houdré, Christian", "tex_files/Houdr%C3%A9%2C%20Christian.tex"], 
           ["Hsing, Tailen", "tex_files/Hsing%2C%20Tailen.tex"], 
           ["Hsiung, Agnes Chao", "tex_files/Hsiung%2C%20Agnes%20Chao.tex"], 
           ["Hsu, Pao-Lu", "tex_files/Hsu%2C%20Pao-Lu.tex"], 
           ["Hu, Feifang", "tex_files/Hu%2C%20Feifang.tex"], 
           ["Hu, Inchi", "tex_files/Hu%2C%20Inchi.tex"], 
           ["Huang, Jianhua Z.", "tex_files/Huang%2C%20Jianhua%20Z..tex"], 
           ["Huber, Peter J.", "tex_files/Huber%2C%20Peter%20J..tex"], 
           ["Huntington, Edward V.", "tex_files/Huntington%2C%20Edward%20V..tex"], 
           ["Hurwitz, William N.", "tex_files/Hurwitz%2C%20William%20N..tex"], 
           ["Hušková, Marie", "tex_files/Hu%C5%A1kov%C3%A1%2C%20Marie.tex"], 
           ["Hwang, J. T. Gene", "tex_files/Hwang%2C%20J.%20T.%20Gene.tex"], 
           ["Hájek, Jaroslav", "tex_files/H%C3%A1jek%2C%20Jaroslav.tex"], 
           ["Härdle, Wolfgang K.", "tex_files/H%C3%A4rdle%2C%20Wolfgang%20K..tex"], 
           ["Ibragimov, Il'dar A.", "tex_files/Ibragimov%2C%20Il%27dar%20A..tex"], 
           ["Ibrahim, Joseph G.", "tex_files/Ibrahim%2C%20Joseph%20G..tex"], 
           ["Iglehart, Donald L.", "tex_files/Iglehart%2C%20Donald%20L..tex"], 
           ["Ingraham, Mark H.", "tex_files/Ingraham%2C%20Mark%20H..tex"], 
           ["Irwin, Joseph Oscar", "tex_files/Irwin%2C%20Joseph%20Oscar.tex"], 
           ["Jackson, Dunham", "tex_files/Jackson%2C%20Dunham.tex"], 
           ["Jacobs, Konrad", "tex_files/Jacobs%2C%20Konrad.tex"], 
           ["Jagers, Peter", "tex_files/Jagers%2C%20Peter.tex"], 
           ["Jain, Naresh C.", "tex_files/Jain%2C%20Naresh%20C..tex"], 
           ["Jakubowski, Adam", "tex_files/Jakubowski%2C%20Adam.tex"], 
           ["James, Alan Treleven", "tex_files/James%2C%20Alan%20Treleven.tex"], 
           ["James, Lancelot F.", "tex_files/James%2C%20Lancelot%20F..tex"], 
           ["Jammalamadaka, Sreenivasa Rao", "tex_files/Jammalamadaka%2C%20Sreenivasa%20Rao.tex"], 
           ["Jenkins, Gwilym M.", "tex_files/Jenkins%2C%20Gwilym%20M..tex"], 
           ["Jennrich, Robert I.", "tex_files/Jennrich%2C%20Robert%20I..tex"], 
           ["Jewell, Nicholas P.", "tex_files/Jewell%2C%20Nicholas%20P..tex"], 
           ["Jiang, Jiming", "tex_files/Jiang%2C%20Jiming.tex"], 
           ["Jin, Jiashun", "tex_files/Jin%2C%20Jiashun.tex"], 
           ["Johansen, Søren", "tex_files/Johansen%2C%20S%C3%B8ren.tex"], 
           ["John, Peter W. M.", "tex_files/John%2C%20Peter%20W.%20M..tex"], 
           ["Johns, M. Vernon, Jr.", "tex_files/Johns%2C%20M.%20Vernon%2C%20Jr..tex"], 
           ["Johnson, Norman L.", "tex_files/Johnson%2C%20Norman%20L..tex"], 
           ["Johnson, Richard A.", "tex_files/Johnson%2C%20Richard%20A..tex"], 
           ["Johnson, Wesley O.", "tex_files/Johnson%2C%20Wesley%20O..tex"], 
           ["Johnstone, Iain M.", "tex_files/Johnstone%2C%20Iain%20M..tex"], 
           ["Jones, M. Chris", "tex_files/Jones%2C%20M.%20Chris.tex"], 
           ["Jordan, Charles", "tex_files/Jordan%2C%20Charles.tex"], 
           ["Jordan, Michael I.", "tex_files/Jordan%2C%20Michael%20I..tex"], 
           ["Joshi, Vinayak M.", "tex_files/Joshi%2C%20Vinayak%20M..tex"], 
           ["Junker, Brian W.", "tex_files/Junker%2C%20Brian%20W..tex"], 
           ["Jurečková, Jana", "tex_files/Jure%C4%8Dkov%C3%A1%2C%20Jana.tex"], 
           ["Kac, Mark", "tex_files/Kac%2C%20Mark.tex"], 
           ["Kadane, Joseph B.", "tex_files/Kadane%2C%20Joseph%20B..tex"], 
           ["Kailath, Thomas", "tex_files/Kailath%2C%20Thomas.tex"], 
           ["Kalbfleisch, John D.", "tex_files/Kalbfleisch%2C%20John%20D..tex"], 
           ["Kallenberg, Olav H.", "tex_files/Kallenberg%2C%20Olav%20H..tex"], 
           ["Kallianpur, Gopinath", "tex_files/Kallianpur%2C%20Gopinath.tex"], 
           ["Kampé de Fériet, Marie-Joseph", "tex_files/Kamp%C3%A9%20de%20F%C3%A9riet%2C%20Marie-Joseph.tex"],
           ["Karatzas, Ioannis", "tex_files/Karatzas%2C%20Ioannis.tex"], 
           ["Kariya, Takeaki", "tex_files/Kariya%2C%20Takeaki.tex"], 
           ["Karlin, Samuel", "tex_files/Karlin%2C%20Samuel.tex"], 
           ["Karr, Alan F.", "tex_files/Karr%2C%20Alan%20F..tex"], 
           ["Kaspi, Haya", "tex_files/Kaspi%2C%20Haya.tex"], 
           ["Kass, Robert E.", "tex_files/Kass%2C%20Robert%20E..tex"], 
           ["Katz, Leo", "tex_files/Katz%2C%20Leo.tex"], 
           ["Kawata, Tatsuo", "tex_files/Kawata%2C%20Tatsuo.tex"], 
           ["Keener, Robert W.", "tex_files/Keener%2C%20Robert%20W..tex"], 
           ["Keiding, Niels", "tex_files/Keiding%2C%20Niels.tex"], 
           ["Keilson, Julian", "tex_files/Keilson%2C%20Julian.tex"], 
           ["Kelley, Truman L.", "tex_files/Kelley%2C%20Truman%20L..tex"], 
           ["Kemperman, Johannes H. B.", "tex_files/Kemperman%2C%20Johannes%20H.%20B..tex"], 
           ["Kempthorne, Oscar", "tex_files/Kempthorne%2C%20Oscar.tex"], 
           ["Kendall, David G.", "tex_files/Kendall%2C%20David%20G..tex"], 
           ["Kendall, Maurice G.", "tex_files/Kendall%2C%20Maurice%20G..tex"], 
           ["Kendall, Wilfrid S.", "tex_files/Kendall%2C%20Wilfrid%20S..tex"], 
           ["Kent, John T.", "tex_files/Kent%2C%20John%20T..tex"], 
           ["Kesten, Harry", "tex_files/Kesten%2C%20Harry.tex"], 
           ["Khas’minskii, Rafail Z.", "tex_files/Khas%E2%80%99minskii%2C%20Rafail%20Z..tex"], 
           ["Khatri, Chinubal G.", "tex_files/Khatri%2C%20Chinubal%20G..tex"], 
           ["Khmaladze, Estate V.", "tex_files/Khmaladze%2C%20Estate%20V..tex"], 
           ["Kiefer, Jack C.", "tex_files/Kiefer%2C%20Jack%20C..tex"], 
           ["Kingman, John F. C.", "tex_files/Kingman%2C%20John%20F.%20C..tex"], 
           ["Kitagawa, Tosio", "tex_files/Kitagawa%2C%20Tosio.tex"], 
           ["Klaassen, Chris A. J.", "tex_files/Klaassen%2C%20Chris%20A.%20J..tex"], 
           ["Klass, Michael J.", "tex_files/Klass%2C%20Michael%20J..tex"], 
           ["Klebaner, Fima C.", "tex_files/Klebaner%2C%20Fima%20C..tex"], 
           ["Klonecki, Witold", "tex_files/Klonecki%2C%20Witold.tex"], 
           ["Klotz, Jerome H.", "tex_files/Klotz%2C%20Jerome%20H..tex"], 
           ["Klüppelberg, Claudia", "tex_files/Kl%C3%BCppelberg%2C%20Claudia.tex"], 
           ["Knight, Frank B.", "tex_files/Knight%2C%20Frank%20B..tex"], 
           ["Koenker, Roger", "tex_files/Koenker%2C%20Roger.tex"], 
           ["Kohn, Robert J.", "tex_files/Kohn%2C%20Robert%20J..tex"], 
           ["Kolassa, John E.", "tex_files/Kolassa%2C%20John%20E..tex"], 
           ["Koltchinskii, Vladimir", "tex_files/Koltchinskii%2C%20Vladimir.tex"], 
           ["Koopmans, Lambert H.", "tex_files/Koopmans%2C%20Lambert%20H..tex"], 
           ["Koopmans, Tjalling C.", "tex_files/Koopmans%2C%20Tjalling%20C..tex"], 
           ["Kosorok, Michael R.", "tex_files/Kosorok%2C%20Michael%20R..tex"], 
           ["Kotz, Samuel", "tex_files/Kotz%2C%20Samuel.tex"], 
           ["Kou, S. C. Samuel", "tex_files/Kou%2C%20S.%20C.%20Samuel.tex"], 
           ["Koul, Hira L.", "tex_files/Koul%2C%20Hira%20L..tex"], 
           ["Koziol, James A.", "tex_files/Koziol%2C%20James%20A..tex"], 
           ["Kraft, Charles H.", "tex_files/Kraft%2C%20Charles%20H..tex"], 
           ["Krengel, Ulrich", "tex_files/Krengel%2C%20Ulrich.tex"], 
           ["Krickeberg, Klaus", "tex_files/Krickeberg%2C%20Klaus.tex"], 
           ["Krieger, Abba M.", "tex_files/Krieger%2C%20Abba%20M..tex"], 
           ["Krishnaiah, Paruchuri R.", "tex_files/Krishnaiah%2C%20Paruchuri%20R..tex"], 
           ["Kruskal, William H.", "tex_files/Kruskal%2C%20William%20H..tex"], 
           ["Kshirsagar, Anant M.", "tex_files/Kshirsagar%2C%20Anant%20M..tex"], 
           ["Kudo, Hirokichi", "tex_files/Kudo%2C%20Hirokichi.tex"], 
           ["Kuelbs, James D.", "tex_files/Kuelbs%2C%20James%20D..tex"], 
           ["Kullback, Solomon", "tex_files/Kullback%2C%20Solomon.tex"], 
           ["Kulldorff, Gunnar", "tex_files/Kulldorff%2C%20Gunnar.tex"], 
           ["Kurtz, Thomas G.", "tex_files/Kurtz%2C%20Thomas%20G..tex"], 
           ["Künsch, Hans R.", "tex_files/K%C3%BCnsch%2C%20Hans%20R..tex"], 
           ["Lagakos, Stephen W.", "tex_files/Lagakos%2C%20Stephen%20W..tex"], 
           ["Laha, Radha G.", "tex_files/Laha%2C%20Radha%20G..tex"], 
           ["Lahiri, Parthasarathi", "tex_files/Lahiri%2C%20Parthasarathi.tex"], 
           ["Lahiri, Soumendra N.", "tex_files/Lahiri%2C%20Soumendra%20N..tex"], 
           ["Lai, Tze Leung", "tex_files/Lai%2C%20Tze%20Leung.tex"], 
           ["Laird, Nan M.", "tex_files/Laird%2C%20Nan%20M..tex"], 
           ["Lalley, Steven P.", "tex_files/Lalley%2C%20Steven%20P..tex"], 
           ["Lambert, Diane M.", "tex_files/Lambert%2C%20Diane%20M..tex"], 
           ["Lamperti, John W.", "tex_files/Lamperti%2C%20John%20W..tex"], 
           ["Lancaster, Henry O.", "tex_files/Lancaster%2C%20Henry%20O..tex"], 
           ["Lane, David A.", "tex_files/Lane%2C%20David%20A..tex"], 
           ["Lange, Kenneth", "tex_files/Lange%2C%20Kenneth.tex"], 
           ["Lauritzen, Steffen L.", "tex_files/Lauritzen%2C%20Steffen%20L..tex"], 
           ["Lawler, Gregory F.", "tex_files/Lawler%2C%20Gregory%20F..tex"], 
           ["Lawless, Jerald F.", "tex_files/Lawless%2C%20Jerald%20F..tex"], 
           ["Le Cam, Lucien M.", "tex_files/Le%20Cam%2C%20Lucien%20M..tex"], 
           ["Le Gall, Jean-François", "tex_files/Le%20Gall%2C%20Jean-Fran%C3%A7ois.tex"], 
           ["Leadbetter, M. Ross", "tex_files/Leadbetter%2C%20M.%20Ross.tex"], 
           ["Ledoux, Michel", "tex_files/Ledoux%2C%20Michel.tex"], 
           ["Lee, Mei-Ling Ting", "tex_files/Lee%2C%20Mei-Ling%20Ting.tex"], 
           ["Lehmann, Erich L.", "tex_files/Lehmann%2C%20Erich%20L..tex"], 
           ["Lehoczky, John P.", "tex_files/Lehoczky%2C%20John%20P..tex"], 
           ["Levene, Howard", "tex_files/Levene%2C%20Howard.tex"], 
           ["Lewis, Peter A. W.", "tex_files/Lewis%2C%20Peter%20A.%20W..tex"], 
           ["Li, Bing", "tex_files/Li%2C%20Bing.tex"], 
           ["Li, Gang", "tex_files/Li%2C%20Gang.tex"], 
           ["Li, Hongzhe", "tex_files/Li%2C%20Hongzhe.tex"], 
           ["Li, Ker-Chau", "tex_files/Li%2C%20Ker-Chau.tex"], 
           ["Li, Runze", "tex_files/Li%2C%20Runze.tex"], 
           ["Li, Wai Keung", "tex_files/Li%2C%20Wai%20Keung.tex"], 
           ["Li, Wenbo V.", "tex_files/Li%2C%20Wenbo%20V..tex"], 
           ["Li, Zenghu", "tex_files/Li%2C%20Zenghu.tex"], 
           ["Liang, Faming", "tex_files/Liang%2C%20Faming.tex"], 
           ["Liang, Hua", "tex_files/Liang%2C%20Hua.tex"], 
           ["Lieberman, Gerald J.", "tex_files/Lieberman%2C%20Gerald%20J..tex"], 
           ["Liggett, Thomas M.", "tex_files/Liggett%2C%20Thomas%20M..tex"], 
           ["Lii, Keh-Shin", "tex_files/Lii%2C%20Keh-Shin.tex"], 
           ["Lin, Danyu", "tex_files/Lin%2C%20Danyu.tex"], 
           ["Lin, Dennis K. J.", "tex_files/Lin%2C%20Dennis%20K.%20J..tex"], 
           ["Lin, Xihong", "tex_files/Lin%2C%20Xihong.tex"], 
           ["Lin, Zhenyang", "tex_files/Lin%2C%20Zhenyang.tex"], 
           ["Linder, Arthur", "tex_files/Linder%2C%20Arthur.tex"], 
           ["Lindgren, Georg", "tex_files/Lindgren%2C%20Georg.tex"], 
           ["Lindley, Dennis V.", "tex_files/Lindley%2C%20Dennis%20V..tex"], 
           ["Lindsay, Bruce G.", "tex_files/Lindsay%2C%20Bruce%20G..tex"], 
           ["Linnik, Yuri V.", "tex_files/Linnik%2C%20Yuri%20V..tex"], 
           ["Linton, Oliver B.", "tex_files/Linton%2C%20Oliver%20B..tex"], 
           ["Liu, Jun", "tex_files/Liu%2C%20Jun.tex"], 
           ["Liu, Regina Y.", "tex_files/Liu%2C%20Regina%20Y..tex"], 
           ["Lloyd, Stuart P.", "tex_files/Lloyd%2C%20Stuart%20P..tex"], 
           ["Lo, Albert Y.", "tex_files/Lo%2C%20Albert%20Y..tex"], 
           ["Lo, Shaw-Hwa", "tex_files/Lo%2C%20Shaw-Hwa.tex"], 
           ["Loh, Wei-Liem", "tex_files/Loh%2C%20Wei-Liem.tex"], 
           ["Loh, Wei-Yin", "tex_files/Loh%2C%20Wei-Yin.tex"], 
           ["Lord, Frederic M.", "tex_files/Lord%2C%20Frederic%20M..tex"], 
           ["Lorden, Gary", "tex_files/Lorden%2C%20Gary.tex"], 
           ["Lotka, Alfred J.", "tex_files/Lotka%2C%20Alfred%20J..tex"], 
           ["Low, Mark G.", "tex_files/Low%2C%20Mark%20G..tex"], 
           ["Loynes, Robert M.", "tex_files/Loynes%2C%20Robert%20M..tex"], 
           ["Loève, Michel", "tex_files/Lo%C3%A8ve%2C%20Michel.tex"], 
           ["Lukacs, Eugene", "tex_files/Lukacs%2C%20Eugene.tex"], 
           ["Lyons, Terence J.", "tex_files/Lyons%2C%20Terence%20J..tex"], 
           ["Ma, Zhi-Ming", "tex_files/Ma%2C%20Zhi-Ming.tex"], 
           ["MacGibbon, K. Brenda", "tex_files/MacGibbon%2C%20K.%20Brenda.tex"], 
           ["MacNeill, Ian B.", "tex_files/MacNeill%2C%20Ian%20B..tex"], 
           ["MacQueen, James B.", "tex_files/MacQueen%2C%20James%20B..tex"], 
           ["Madansky, Albert", "tex_files/Madansky%2C%20Albert.tex"], 
           ["Madigan, David", "tex_files/Madigan%2C%20David.tex"], 
           ["Madow, William G.", "tex_files/Madow%2C%20William%20G..tex"], 
           ["Madras, Neal N.", "tex_files/Madras%2C%20Neal%20N..tex"], 
           ["Maiti, Tapabrata", "tex_files/Maiti%2C%20Tapabrata.tex"], 
           ["Mallick, Bani K.", "tex_files/Mallick%2C%20Bani%20K..tex"], 
           ["Mallows, Colin L.", "tex_files/Mallows%2C%20Colin%20L..tex"], 
           ["Mammen, Enno", "tex_files/Mammen%2C%20Enno.tex"], 
           ["Mandelbrot, Benoit B.", "tex_files/Mandelbrot%2C%20Benoit%20B..tex"], 
           ["Mann, Henry B.", "tex_files/Mann%2C%20Henry%20B..tex"], 
           ["Mantel, Nathan", "tex_files/Mantel%2C%20Nathan.tex"], 
           ["Marcus, Michael B.", "tex_files/Marcus%2C%20Michael%20B..tex"], 
           ["Marden, John I.", "tex_files/Marden%2C%20John%20I..tex"], 
           ["Mardia, Kantilal V.", "tex_files/Mardia%2C%20Kantilal%20V..tex"], 
           ["Maritz, Johannes S.", "tex_files/Maritz%2C%20Johannes%20S..tex"], 
           ["Marron, James Stephen", "tex_files/Marron%2C%20James%20Stephen.tex"], 
           ["Marschak, Jacob", "tex_files/Marschak%2C%20Jacob.tex"], 
           ["Marshall, Albert W.", "tex_files/Marshall%2C%20Albert%20W..tex"], 
           ["Martinsek, Adam T.", "tex_files/Martinsek%2C%20Adam%20T..tex"], 
           ["Mason, David M.", "tex_files/Mason%2C%20David%20M..tex"], 
           ["Massam, Hélène M.", "tex_files/Massam%2C%20H%C3%A9l%C3%A8ne%20M..tex"], 
           ["Masuyama, Motosaburo", "tex_files/Masuyama%2C%20Motosaburo.tex"], 
           ["Mathai, A. M.", "tex_files/Mathai%2C%20A.%20M..tex"], 
           ["Mathew, Thomas", "tex_files/Mathew%2C%20Thomas.tex"], 
           ["Mattingly, Jonathan C.", "tex_files/Mattingly%2C%20Jonathan%20C..tex"], 
           ["Matusita, Kameo", "tex_files/Matusita%2C%20Kameo.tex"], 
           ["Matérn, Bertil", "tex_files/Mat%C3%A9rn%2C%20Bertil.tex"], 
           ["McCullagh, Peter", "tex_files/McCullagh%2C%20Peter.tex"], 
           ["McDonald, David R.", "tex_files/McDonald%2C%20David%20R..tex"], 
           ["McDonald, Gary C.", "tex_files/McDonald%2C%20Gary%20C..tex"], 
           ["McKeague, Ian W.", "tex_files/McKeague%2C%20Ian%20W..tex"], 
           ["McLeish, Don L.", "tex_files/McLeish%2C%20Don%20L..tex"], 
           ["Meeden, Glen D.", "tex_files/Meeden%2C%20Glen%20D..tex"], 
           ["Meier, Paul", "tex_files/Meier%2C%20Paul.tex"], 
           ["Meng, Xiao-Li", "tex_files/Meng%2C%20Xiao-Li.tex"], 
           ["Mengersen, Kerrie Lee", "tex_files/Mengersen%2C%20Kerrie%20Lee.tex"], 
           ["Meyer, Paul L.", "tex_files/Meyer%2C%20Paul%20L..tex"], 
           ["Michailidis, George", "tex_files/Michailidis%2C%20George.tex"], 
           ["Mikosch, Thomas", "tex_files/Mikosch%2C%20Thomas.tex"], 
           ["Millar, P. Warwick", "tex_files/Millar%2C%20P.%20Warwick.tex"], 
           ["Miller, Rupert G., Jr.", "tex_files/Miller%2C%20Rupert%20G.%2C%20Jr..tex"], 
           ["Mitra, S. K.", "tex_files/Mitra%2C%20S.%20K..tex"], 
           ["Mittal, Yashaswini D.", "tex_files/Mittal%2C%20Yashaswini%20D..tex"], 
           ["Molina, Edward C.", "tex_files/Molina%2C%20Edward%20C..tex"], 
           ["Mood, Alexander M.", "tex_files/Mood%2C%20Alexander%20M..tex"], 
           ["Moore, David S.", "tex_files/Moore%2C%20David%20S..tex"], 
           ["Moriguti, Sigeiti", "tex_files/Moriguti%2C%20Sigeiti.tex"], 
           ["Morris, Carl N.", "tex_files/Morris%2C%20Carl%20N..tex"], 
           ["Morrison, Donald F.", "tex_files/Morrison%2C%20Donald%20F..tex"], 
           ["Moses, Lincoln E.", "tex_files/Moses%2C%20Lincoln%20E..tex"], 
           ["Mosteller, Frederick", "tex_files/Mosteller%2C%20Frederick.tex"], 
           ["Motoo, Minoru", "tex_files/Motoo%2C%20Minoru.tex"], 
           ["Mountford, Thomas S.", "tex_files/Mountford%2C%20Thomas%20S..tex"], 
           ["Mudholkar, Govind S.", "tex_files/Mudholkar%2C%20Govind%20S..tex"], 
           ["Muirhead, Robb J.", "tex_files/Muirhead%2C%20Robb%20J..tex"], 
           ["Mukerjee, Rahul", "tex_files/Mukerjee%2C%20Rahul.tex"], 
           ["Mukhopadhyay, Nitis", "tex_files/Mukhopadhyay%2C%20Nitis.tex"], 
           ["Murphy, Susan A.", "tex_files/Murphy%2C%20Susan%20A..tex"], 
           ["Mykland, Per A.", "tex_files/Mykland%2C%20Per%20A..tex"], 
           ["Mytnik, Leonid", "tex_files/Mytnik%2C%20Leonid.tex"], 
           ["Müller, Hans-Georg", "tex_files/M%C3%BCller%2C%20Hans-Georg.tex"], 
           ["Müller, Peter", "tex_files/M%C3%BCller%2C%20Peter.tex"], 
           ["Naiman, Daniel Q.", "tex_files/Naiman%2C%20Daniel%20Q..tex"], 
           ["Nair, Vijayan N.", "tex_files/Nair%2C%20Vijayan%20N..tex"], 
           ["Neuts, Marcel F.", "tex_files/Neuts%2C%20Marcel%20F..tex"], 
           ["Neveu, Jacques", "tex_files/Neveu%2C%20Jacques.tex"], 
           ["Newman, Charles M.", "tex_files/Newman%2C%20Charles%20M..tex"], 
           ["Ney, Peter E.", "tex_files/Ney%2C%20Peter%20E..tex"], 
           ["Neyman, Jerzy", "tex_files/Neyman%2C%20Jerzy.tex"], 
           ["Nicholson, George E., Jr.", "tex_files/Nicholson%2C%20George%20E.%2C%20Jr..tex"], 
           ["Nikitin, Yakov", "tex_files/Nikitin%2C%20Yakov.tex"], 
           ["Nobel, Andrew B.", "tex_files/Nobel%2C%20Andrew%20B..tex"], 
           ["Noether, Gottfried E.", "tex_files/Noether%2C%20Gottfried%20E..tex"], 
           ["Nolan, Deborah", "tex_files/Nolan%2C%20Deborah.tex"], 
           ["Nualart, David", "tex_files/Nualart%2C%20David.tex"], 
           ["Nummelin, Esa I.", "tex_files/Nummelin%2C%20Esa%20I..tex"], 
           ["Nussbaum, Michael", "tex_files/Nussbaum%2C%20Michael.tex"], 
           ["O'Brien, George L.", "tex_files/O%27Brien%2C%20George%20L..tex"], 
           ["O'Neill, Terence J.", "tex_files/O%27Neill%2C%20Terence%20J..tex"], 
           ["O'Toole, Alphonsus L.", "tex_files/O%27Toole%2C%20Alphonsus%20L..tex"], 
           ["Oakes, David", "tex_files/Oakes%2C%20David.tex"], 
           ["Odeh, Robert E.", "tex_files/Odeh%2C%20Robert%20E..tex"], 
           ["Ogawa, Junjiro", "tex_files/Ogawa%2C%20Junjiro.tex"], 
           ["Oja, Hannu", "tex_files/Oja%2C%20Hannu.tex"], 
           ["Olds, Edwin G.", "tex_files/Olds%2C%20Edwin%20G..tex"], 
           ["Olkin, Ingram", "tex_files/Olkin%2C%20Ingram.tex"], 
           ["Olshen, Richard A.", "tex_files/Olshen%2C%20Richard%20A..tex"], 
           ["Oosterhoff, Jacobus", "tex_files/Oosterhoff%2C%20Jacobus.tex"], 
           ["Opsomer, Jean D.", "tex_files/Opsomer%2C%20Jean%20D..tex"], 
           ["Owen, Art B.", "tex_files/Owen%2C%20Art%20B..tex"], 
           ["Owen, Donald B.", "tex_files/Owen%2C%20Donald%20B..tex"], 
           ["Padgett, William J.", "tex_files/Padgett%2C%20William%20J..tex"], 
           ["Papangelou, Fredos", "tex_files/Papangelou%2C%20Fredos.tex"], 
           ["Park, Byeong U.", "tex_files/Park%2C%20Byeong%20U..tex"], 
           ["Parthasarathy, P. R.", "tex_files/Parthasarathy%2C%20P.%20R..tex"], 
           ["Parzen, Emanuel", "tex_files/Parzen%2C%20Emanuel.tex"], 
           ["Pathak, Pramod K.", "tex_files/Pathak%2C%20Pramod%20K..tex"], 
           ["Patil, Ganapati P.", "tex_files/Patil%2C%20Ganapati%20P..tex"], 
           ["Paulson, Edward", "tex_files/Paulson%2C%20Edward.tex"], 
           ["Pearson, Egon S.", "tex_files/Pearson%2C%20Egon%20S..tex"], 
           ["Peligrad, Magda", "tex_files/Peligrad%2C%20Magda.tex"], 
           ["Pemantle, Robin", "tex_files/Pemantle%2C%20Robin.tex"], 
           ["Peng, Liang", "tex_files/Peng%2C%20Liang.tex"], 
           ["Peng, Shige", "tex_files/Peng%2C%20Shige.tex"], 
           ["Peres, Yuval", "tex_files/Peres%2C%20Yuval.tex"], 
           ["Perkins, Edwin A.", "tex_files/Perkins%2C%20Edwin%20A..tex"], 
           ["Perlman, Michael D.", "tex_files/Perlman%2C%20Michael%20D..tex"], 
           ["Peña Sánchez de Rivera, Daniel", "tex_files/Pe%C3%B1a%20S%C3%A1nchez%20de%20Rivera%2C%20Daniel.tex"],
           ["Pfanzagl, Johann", "tex_files/Pfanzagl%2C%20Johann.tex"], 
           ["Philipp, Walter", "tex_files/Philipp%2C%20Walter.tex"], 
           ["Phillips, Peter C. B.", "tex_files/Phillips%2C%20Peter%20C.%20B..tex"], 
           ["Pierce, Donald A.", "tex_files/Pierce%2C%20Donald%20A..tex"], 
           ["Pillai, K. C. S.", "tex_files/Pillai%2C%20K.%20C.%20S..tex"], 
           ["Pinsky, Mark A.", "tex_files/Pinsky%2C%20Mark%20A..tex"], 
           ["Pisier, Gilles I.", "tex_files/Pisier%2C%20Gilles%20I..tex"], 
           ["Pitman, Edwin J. G.", "tex_files/Pitman%2C%20Edwin%20J.%20G..tex"], 
           ["Pitman, James W.", "http://www.stat.berkeley.edu/~pitman/Pitman_James_W_IMS_data.tex"]
           ["Pitt, Loren D.", "tex_files/Pitt%2C%20Loren%20D..tex"], 
           ["Pittenger, Arthur O.", "tex_files/Pittenger%2C%20Arthur%20O..tex"], 
           ["Plackett, Robin L.", "tex_files/Plackett%2C%20Robin%20L..tex"], 
           ["Politis, Dimitris N.", "tex_files/Politis%2C%20Dimitris%20N..tex"], 
           ["Pollak, Moshe", "tex_files/Pollak%2C%20Moshe.tex"], 
           ["Pollard, David", "tex_files/Pollard%2C%20David.tex"], 
           ["Polonik, Wolfgang", "tex_files/Polonik%2C%20Wolfgang.tex"], 
           ["Polzehl, Jörg", "tex_files/Polzehl%2C%20J%C3%B6rg.tex"], 
           ["Poor, Harold Vincent", "tex_files/Poor%2C%20Harold%20Vincent.tex"], 
           ["Port, Sidney C.", "tex_files/Port%2C%20Sidney%20C..tex"], 
           ["Portnoy, Stephen L.", "tex_files/Portnoy%2C%20Stephen%20L..tex"], 
           ["Prabhu, Narahari U.", "tex_files/Prabhu%2C%20Narahari%20U..tex"], 
           ["Prakasa-Rao, B. L. S.", "tex_files/Prakasa-Rao%2C%20B.%20L.%20S..tex"], 
           ["Pratt, John W.", "tex_files/Pratt%2C%20John%20W..tex"], 
           ["Press, S. James", "tex_files/Press%2C%20S.%20James.tex"], 
           ["Priestley, Maurice B.", "tex_files/Priestley%2C%20Maurice%20B..tex"], 
           ["Proschan, Frank", "tex_files/Proschan%2C%20Frank.tex"], 
           ["Protter, Philip E.", "tex_files/Protter%2C%20Philip%20E..tex"], 
           ["Pruitt, William E.", "tex_files/Pruitt%2C%20William%20E..tex"], 
           ["Pukelsheim, Friedrich", "tex_files/Pukelsheim%2C%20Friedrich.tex"], 
           ["Purdue, Peter", "tex_files/Purdue%2C%20Peter.tex"], 
           ["Puri, Madan L.", "tex_files/Puri%2C%20Madan%20L..tex"], 
           ["Puri, Prem S.", "tex_files/Puri%2C%20Prem%20S..tex"], 
           ["Pyke, Ronald", "tex_files/Pyke%2C%20Ronald.tex"], 
           ["Pérez-Abreu, Víctor M.", "tex_files/P%C3%A9rez-Abreu%2C%20V%C3%ADctor%20M..tex"], 
           ["Qiu, Peihua", "tex_files/Qiu%2C%20Peihua.tex"], 
           ["Quenouille, Maurice H.", "tex_files/Quenouille%2C%20Maurice%20H..tex"], 
           ["Rachev, Svetlozar T.", "tex_files/Rachev%2C%20Svetlozar%20T..tex"], 
           ["Raftery, Adrian E.", "tex_files/Raftery%2C%20Adrian%20E..tex"], 
           ["Raghavachari, Madabhushi", "tex_files/Raghavachari%2C%20Madabhushi.tex"], 
           ["Raghavarao, Damaraju", "tex_files/Raghavarao%2C%20Damaraju.tex"], 
           ["Raiffa, Howard", "tex_files/Raiffa%2C%20Howard.tex"], 
           ["Raktoe, B. Leo", "tex_files/Raktoe%2C%20B.%20Leo.tex"], 
           ["Ramanan, Kavita", "tex_files/Ramanan%2C%20Kavita.tex"], 
           ["Randles, Ronald H.", "tex_files/Randles%2C%20Ronald%20H..tex"], 
           ["Rao, Calyampudi Radhakrishna", "tex_files/Rao%2C%20Calyampudi%20Radhakrishna.tex"], 
           ["Rao, Jonnagadda N. K.", "tex_files/Rao%2C%20Jonnagadda%20N.%20K..tex"], 
           ["Rao, Malempati M.", "tex_files/Rao%2C%20Malempati%20M..tex"], 
           ["Rao, Marepalli Bhaskara", "tex_files/Rao%2C%20Marepalli%20Bhaskara.tex"], 
           ["Rasch, Dieter", "tex_files/Rasch%2C%20Dieter.tex"], 
           ["Reed, Lowell J.", "tex_files/Reed%2C%20Lowell%20J..tex"], 
           ["Regazzini, Eugenio", "tex_files/Regazzini%2C%20Eugenio.tex"], 
           ["Reid, Nancy M.", "tex_files/Reid%2C%20Nancy%20M..tex"], 
           ["Reiersøl, Olav", "tex_files/Reiers%C3%B8l%2C%20Olav.tex"], 
           ["Reinsel, Gregory C.", "tex_files/Reinsel%2C%20Gregory%20C..tex"], 
           ["Reiß, Rolf-Dieter", "tex_files/Rei%C3%9F%2C%20Rolf-Dieter.tex"], 
           ["Resnick, Sidney I.", "tex_files/Resnick%2C%20Sidney%20I..tex"], 
           ["Resnikoff, George J.", "tex_files/Resnikoff%2C%20George%20J..tex"], 
           ["Rice, John A.", "tex_files/Rice%2C%20John%20A..tex"], 
           ["Richards, Donald St. P.", "tex_files/Richards%2C%20Donald%20St.%20P..tex"], 
           ["Rider, Paul R.", "tex_files/Rider%2C%20Paul%20R..tex"], 
           ["Rietz, Henry L.", "tex_files/Rietz%2C%20Henry%20L..tex"], 
           ["Rinott, Yosef", "tex_files/Rinott%2C%20Yosef.tex"], 
           ["Riordan, John", "tex_files/Riordan%2C%20John.tex"], 
           ["Ripley, Brian D.", "tex_files/Ripley%2C%20Brian%20D..tex"], 
           ["Ritov, Ya'acov", "tex_files/Ritov%2C%20Ya%27acov.tex"], 
           ["Robbins, Herbert E.", "tex_files/Robbins%2C%20Herbert%20E..tex"], 
           ["Robert, Christian P.", "tex_files/Robert%2C%20Christian%20P..tex"], 
           ["Robertson, Timothy J.", "tex_files/Robertson%2C%20Timothy%20J..tex"], 
           ["Robinson, John", "tex_files/Robinson%2C%20John.tex"], 
           ["Robinson, Peter M.", "tex_files/Robinson%2C%20Peter%20M..tex"], 
           ["Roeder, Kathryn", "tex_files/Roeder%2C%20Kathryn.tex"], 
           ["Rojo, Javier", "tex_files/Rojo%2C%20Javier.tex"], 
           ["Rolph, John E.", "tex_files/Rolph%2C%20John%20E..tex"], 
           ["Romano, Joseph P.", "tex_files/Romano%2C%20Joseph%20P..tex"], 
           ["Roos, Charles F.", "tex_files/Roos%2C%20Charles%20F..tex"], 
           ["Rootzén, Holger", "tex_files/Rootz%C3%A9n%2C%20Holger.tex"], 
           ["Rosen, Jay S.", "tex_files/Rosen%2C%20Jay%20S..tex"], 
           ["Rosenberger, William F.", "tex_files/Rosenberger%2C%20William%20F..tex"], 
           ["Rosenblatt, Joan R.", "tex_files/Rosenblatt%2C%20Joan%20R..tex"], 
           ["Rosenblatt, Judah I.", "tex_files/Rosenblatt%2C%20Judah%20I..tex"], 
           ["Rosenblatt, Murray", "tex_files/Rosenblatt%2C%20Murray.tex"], 
           ["Rosenthal, Jeffrey S.", "tex_files/Rosenthal%2C%20Jeffrey%20S..tex"], 
           ["Rosinski, Jan", "tex_files/Rosinski%2C%20Jan.tex"], 
           ["Ross, Sheldon M.", "tex_files/Ross%2C%20Sheldon%20M..tex"], 
           ["Rota, Gian-Carlo", "tex_files/Rota%2C%20Gian-Carlo.tex"], 
           ["Roussas, George G.", "tex_files/Roussas%2C%20George%20G..tex"], 
           ["Rousseeuw, Peter J.", "tex_files/Rousseeuw%2C%20Peter%20J..tex"], 
           ["Roy, Samarendra N.", "tex_files/Roy%2C%20Samarendra%20N..tex"], 
           ["Rozovsky, Boris L.", "tex_files/Rozovsky%2C%20Boris%20L..tex"], 
           ["Ruben, Harold", "tex_files/Ruben%2C%20Harold.tex"], 
           ["Rubin, Donald B.", "tex_files/Rubin%2C%20Donald%20B..tex"], 
           ["Rubin, Herman", "tex_files/Rubin%2C%20Herman.tex"], 
           ["Rukhin, Andrew L.", "tex_files/Rukhin%2C%20Andrew%20L..tex"], 
           ["Ruppert, David", "tex_files/Ruppert%2C%20David.tex"], 
           ["Rustagi, Jagdish S.", "tex_files/Rustagi%2C%20Jagdish%20S..tex"], 
           ["Ruymgaart, Frits H.", "tex_files/Ruymgaart%2C%20Frits%20H..tex"], 
           ["Rényi, Alfréd", "tex_files/R%C3%A9nyi%2C%20Alfr%C3%A9d.tex"], 
           ["Révész, Pál", "tex_files/R%C3%A9v%C3%A9sz%2C%20P%C3%A1l.tex"], 
           ["Ríos Garcia, Sixto", "tex_files/R%C3%ADos%20Garcia%2C%20Sixto.tex"], 
           ["Sackrowitz, Harold B.", "tex_files/Sackrowitz%2C%20Harold%20B..tex"], 
           ["Sacks, Jerome", "tex_files/Sacks%2C%20Jerome.tex"], 
           ["Saleh, A. K. Md. Ehsanes", "tex_files/Saleh%2C%20A.%20K.%20Md.%20Ehsanes.tex"], 
           ["Salisbury, Thomas S.", "tex_files/Salisbury%2C%20Thomas%20S..tex"], 
           ["Saloff-Coste, Laurent", "tex_files/Saloff-Coste%2C%20Laurent.tex"], 
           ["Samaniego, Francisco J.", "tex_files/Samaniego%2C%20Francisco%20J..tex"], 
           ["Samorodnitsky, Gennady", "tex_files/Samorodnitsky%2C%20Gennady.tex"], 
           ["Sampson, Allan R.", "tex_files/Sampson%2C%20Allan%20R..tex"], 
           ["Samuel-Cahn, Ester", "tex_files/Samuel-Cahn%2C%20Ester.tex"], 
           ["Santner, Thomas J.", "tex_files/Santner%2C%20Thomas%20J..tex"], 
           ["Sanz-Solé, Marta", "tex_files/Sanz-Sol%C3%A9%2C%20Marta.tex"], 
           ["Sarkar, Sanat K.", "tex_files/Sarkar%2C%20Sanat%20K..tex"], 
           ["Savage, I. Richard", "tex_files/Savage%2C%20I.%20Richard.tex"], 
           ["Savage, Leonard J.", "tex_files/Savage%2C%20Leonard%20J..tex"], 
           ["Savits, Thomas H.", "tex_files/Savits%2C%20Thomas%20H..tex"], 
           ["Sawyer, Stanley A.", "tex_files/Sawyer%2C%20Stanley%20A..tex"], 
           ["Scheffé, Henry", "tex_files/Scheff%C3%A9%2C%20Henry.tex"], 
           ["Schervish, Mark J.", "tex_files/Schervish%2C%20Mark%20J..tex"], 
           ["Schmetterer, Leopold K.", "tex_files/Schmetterer%2C%20Leopold%20K..tex"], 
           ["Schonmann, Roberto H.", "tex_files/Schonmann%2C%20Roberto%20H..tex"], 
           ["Schuster, Eugene F.", "tex_files/Schuster%2C%20Eugene%20F..tex"], 
           ["Schwarz, Gideon E.", "tex_files/Schwarz%2C%20Gideon%20E..tex"], 
           ["Scott, Alastair J.", "tex_files/Scott%2C%20Alastair%20J..tex"], 
           ["Scott, David W.", "tex_files/Scott%2C%20David%20W..tex"], 
           ["Scott, Elizabeth L.", "tex_files/Scott%2C%20Elizabeth%20L..tex"], 
           ["Seely, Justus F.", "tex_files/Seely%2C%20Justus%20F..tex"], 
           ["Seiden, Esther", "tex_files/Seiden%2C%20Esther.tex"], 
           ["Sellke, Thomas M.", "tex_files/Sellke%2C%20Thomas%20M..tex"], 
           ["Sen, Pranab K.", "tex_files/Sen%2C%20Pranab%20K..tex"], 
           ["Seppäläinen, Timo", "tex_files/Sepp%C3%A4l%C3%A4inen%2C%20Timo.tex"], 
           ["Serfling, Robert J.", "tex_files/Serfling%2C%20Robert%20J..tex"], 
           ["Serfozo, Richard F.", "tex_files/Serfozo%2C%20Richard%20F..tex"], 
           ["Sethuraman, Jayaram", "tex_files/Sethuraman%2C%20Jayaram.tex"], 
           ["Severo, Norman C.", "tex_files/Severo%2C%20Norman%20C..tex"], 
           ["Shafer, Glenn", "tex_files/Shafer%2C%20Glenn.tex"], 
           ["Shaked, Moshe", "tex_files/Shaked%2C%20Moshe.tex"], 
           ["Shaman, Paul", "tex_files/Shaman%2C%20Paul.tex"], 
           ["Shao, Jun", "tex_files/Shao%2C%20Jun.tex"], 
           ["Shao, Qi-Man", "tex_files/Shao%2C%20Qi-Man.tex"], 
           ["Sharpe, Michael J.", "tex_files/Sharpe%2C%20Michael%20J..tex"], 
           ["Shen, Xiaotong", "tex_files/Shen%2C%20Xiaotong.tex"], 
           ["Shepp, Lawrence A.", "tex_files/Shepp%2C%20Lawrence%20A..tex"], 
           ["Shewhart, Walter A.", "tex_files/Shewhart%2C%20Walter%20A..tex"], 
           ["Shohat, James A.", "tex_files/Shohat%2C%20James%20A..tex"], 
           ["Shorack, Galen R.", "tex_files/Shorack%2C%20Galen%20R..tex"], 
           ["Shreve, Steven E.", "tex_files/Shreve%2C%20Steven%20E..tex"], 
           ["Shrikhande, S. S.", "tex_files/Shrikhande%2C%20S.%20S..tex"], 
           ["Siegmund, David O.", "tex_files/Siegmund%2C%20David%20O..tex"], 
           ["Silverman, Bernard W.", "tex_files/Silverman%2C%20Bernard%20W..tex"], 
           ["Silverstein, Jack W.", "tex_files/Silverstein%2C%20Jack%20W..tex"], 
           ["Silvey, Samuel D.", "tex_files/Silvey%2C%20Samuel%20D..tex"], 
           ["Simon, Leslie E.", "tex_files/Simon%2C%20Leslie%20E..tex"], 
           ["Simonoff, Jeffrey S.", "tex_files/Simonoff%2C%20Jeffrey%20S..tex"], 
           ["Simons, Gordon D.", "tex_files/Simons%2C%20Gordon%20D..tex"], 
           ["Simpson, Douglas G.", "tex_files/Simpson%2C%20Douglas%20G..tex"], 
           ["Singh, Kesar", "tex_files/Singh%2C%20Kesar.tex"], 
           ["Singpurwalla, Nozer D.", "tex_files/Singpurwalla%2C%20Nozer%20D..tex"], 
           ["Sinha, Bimal K.", "tex_files/Sinha%2C%20Bimal%20K..tex"], 
           ["Sitgreaves-Bowker, Rosedith", "tex_files/Sitgreaves-Bowker%2C%20Rosedith.tex"], 
           ["Slade, Gordon", "tex_files/Slade%2C%20Gordon.tex"], 
           ["Slepian, David S.", "tex_files/Slepian%2C%20David%20S..tex"], 
           ["Slud, Eric V.", "tex_files/Slud%2C%20Eric%20V..tex"], 
           ["Smith, Adrian F. M.", "tex_files/Smith%2C%20Adrian%20F.%20M..tex"], 
           ["Smith, Richard L.", "tex_files/Smith%2C%20Richard%20L..tex"], 
           ["Smith, Walter L.", "tex_files/Smith%2C%20Walter%20L..tex"], 
           ["Smythe, Robert T.", "tex_files/Smythe%2C%20Robert%20T..tex"], 
           ["Snedecor, George W.", "tex_files/Snedecor%2C%20George%20W..tex"], 
           ["Snell, J. Laurie", "tex_files/Snell%2C%20J.%20Laurie.tex"], 
           ["Sobel, Milton", "tex_files/Sobel%2C%20Milton.tex"], 
           ["Solomon, Herbert", "tex_files/Solomon%2C%20Herbert.tex"], 
           ["Speckman, Paul L.", "tex_files/Speckman%2C%20Paul%20L..tex"], 
           ["Speed, Terence P.", "tex_files/Speed%2C%20Terence%20P..tex"], 
           ["Spiegelman, Clifford H.", "tex_files/Spiegelman%2C%20Clifford%20H..tex"], 
           ["Spitzer, Frank L.", "tex_files/Spitzer%2C%20Frank%20L..tex"], 
           ["Spjøtvoll, Emil O.", "tex_files/Spj%C3%B8tvoll%2C%20Emil%20O..tex"], 
           ["Spokoiny, Vladimir", "tex_files/Spokoiny%2C%20Vladimir.tex"], 
           ["Sprott, David A.", "tex_files/Sprott%2C%20David%20A..tex"], 
           ["Srivastava, Jagdish N.", "tex_files/Srivastava%2C%20Jagdish%20N..tex"], 
           ["Srivastava, Muni S.", "tex_files/Srivastava%2C%20Muni%20S..tex"], 
           ["Steele, J. Michael", "tex_files/Steele%2C%20J.%20Michael.tex"], 
           ["Stein, Charles M.", "tex_files/Stein%2C%20Charles%20M..tex"], 
           ["Stein, Michael L.", "tex_files/Stein%2C%20Michael%20L..tex"], 
           ["Stephan, Frederick F.", "tex_files/Stephan%2C%20Frederick%20F..tex"], 
           ["Stephens, Michael A.", "tex_files/Stephens%2C%20Michael%20A..tex"], 
           ["Stern, Hal S.", "tex_files/Stern%2C%20Hal%20S..tex"], 
           ["Stigler, Stephen M.", "tex_files/Stigler%2C%20Stephen%20M..tex"], 
           ["Stone, Charles J.", "tex_files/Stone%2C%20Charles%20J..tex"], 
           ["Storey, John D.", "tex_files/Storey%2C%20John%20D..tex"], 
           ["Stout, William F.", "tex_files/Stout%2C%20William%20F..tex"], 
           ["Stoyan, Dietrich", "tex_files/Stoyan%2C%20Dietrich.tex"], 
           ["Strawderman, Robert L.", "tex_files/Strawderman%2C%20Robert%20L..tex"], 
           ["Strawderman, William E.", "tex_files/Strawderman%2C%20William%20E..tex"], 
           ["Stuart, Alan", "tex_files/Stuart%2C%20Alan.tex"], 
           ["Studden, William J.", "tex_files/Studden%2C%20William%20J..tex"], 
           ["Stufken, John", "tex_files/Stufken%2C%20John.tex"], 
           ["Stute, Winfried", "tex_files/Stute%2C%20Winfried.tex"], 
           ["Styan, George P. H.", "tex_files/Styan%2C%20George%20P.%20H..tex"], 
           ["Sudderth, William D.", "tex_files/Sudderth%2C%20William%20D..tex"], 
           ["Sun, Dongchu", "tex_files/Sun%2C%20Dongchu.tex"], 
           ["Sun, Jianguo", "tex_files/Sun%2C%20Jianguo.tex"], 
           ["Sun, Jiayang", "tex_files/Sun%2C%20Jiayang.tex"], 
           ["Susarla, Vyaghreshwarudu", "tex_files/Susarla%2C%20Vyaghreshwarudu.tex"], 
           ["Sverdrup, Erling", "tex_files/Sverdrup%2C%20Erling.tex"], 
           ["Switzer, Paul", "tex_files/Switzer%2C%20Paul.tex"], 
           ["Syski, Ryszard", "tex_files/Syski%2C%20Ryszard.tex"], 
           ["Sznitman, Alain-Sol", "tex_files/Sznitman%2C%20Alain-Sol.tex"], 
           ["Székely, Gábor J.", "tex_files/Sz%C3%A9kely%2C%20G%C3%A1bor%20J..tex"], 
           ["Särndal, Carl-Erik", "tex_files/S%C3%A4rndal%2C%20Carl-Erik.tex"], 
           ["Sørensen, Michael", "tex_files/S%C3%B8rensen%2C%20Michael.tex"], 
           ["Takeuchi, Kei", "tex_files/Takeuchi%2C%20Kei.tex"], 
           ["Takács, Lajos F.", "tex_files/Tak%C3%A1cs%2C%20Lajos%20F..tex"], 
           ["Tamhane, Ajit C.", "tex_files/Tamhane%2C%20Ajit%20C..tex"], 
           ["Tang, Boxin", "tex_files/Tang%2C%20Boxin.tex"], 
           ["Taniguchi, Masanobu", "tex_files/Taniguchi%2C%20Masanobu.tex"], 
           ["Taqqu, Murad S.", "tex_files/Taqqu%2C%20Murad%20S..tex"], 
           ["Tartakovsky, Alexander G.", "tex_files/Tartakovsky%2C%20Alexander%20G..tex"], 
           ["Tate, Robert F.", "tex_files/Tate%2C%20Robert%20F..tex"], 
           ["Tavaré, Simon", "tex_files/Tavar%C3%A9%2C%20Simon.tex"], 
           ["Taylor, Howard M., III", "tex_files/Taylor%2C%20Howard%20M.%2C%20III.tex"], 
           ["Taylor, Robert L.", "tex_files/Taylor%2C%20Robert%20L..tex"], 
           ["Taylor, S. James", "tex_files/Taylor%2C%20S.%20James.tex"], 
           ["Teicher, Henry", "tex_files/Teicher%2C%20Henry.tex"], 
           ["Teugels, Jozef L.", "tex_files/Teugels%2C%20Jozef%20L..tex"], 
           ["Theodorescu, Radu A. S.", "tex_files/Theodorescu%2C%20Radu%20A.%20S..tex"], 
           ["Thompson, James R.", "tex_files/Thompson%2C%20James%20R..tex"], 
           ["Thompson, Mary E.", "tex_files/Thompson%2C%20Mary%20E..tex"], 
           ["Thompson, William R.", "tex_files/Thompson%2C%20William%20R..tex"], 
           ["Thorp, Edward O.", "tex_files/Thorp%2C%20Edward%20O..tex"], 
           ["Tiago da Fonseca Oliveira, José", "tex_files/Tiago%20da%20Fonseca%20Oliveira%2C%20Jos%C3%A9.tex"],
           ["Tiao, George C.", "tex_files/Tiao%2C%20George%20C..tex"], 
           ["Tibshirani, Robert J.", "tex_files/Tibshirani%2C%20Robert%20J..tex"], 
           ["Tierney, Luke", "tex_files/Tierney%2C%20Luke.tex"], 
           ["Tintner, Gerhard", "tex_files/Tintner%2C%20Gerhard.tex"], 
           ["Titterington, Donald Michael", "tex_files/Titterington%2C%20Donald%20Michael.tex"], 
           ["Tong, Howell", "tex_files/Tong%2C%20Howell.tex"], 
           ["Tong, Yung L.", "tex_files/Tong%2C%20Yung%20L..tex"], 
           ["Torgersen, Erik N.", "tex_files/Torgersen%2C%20Erik%20N..tex"], 
           ["Tran, Lanh Tat", "tex_files/Tran%2C%20Lanh%20Tat.tex"], 
           ["Truax, Donald R.", "tex_files/Truax%2C%20Donald%20R..tex"], 
           ["Trumbo, Bruce E.", "tex_files/Trumbo%2C%20Bruce%20E..tex"], 
           ["Tsay, Ruey S.", "tex_files/Tsay%2C%20Ruey%20S..tex"], 
           ["Tsiatis, Anastasios A.", "tex_files/Tsiatis%2C%20Anastasios%20A..tex"], 
           ["Tsybakov, Alexandre B.", "tex_files/Tsybakov%2C%20Alexandre%20B..tex"], 
           ["Tucker, Howard G.", "tex_files/Tucker%2C%20Howard%20G..tex"], 
           ["Tukey, John W.", "tex_files/Tukey%2C%20John%20W..tex"], 
           ["Tusnády, Gábor", "tex_files/Tusn%C3%A1dy%2C%20G%C3%A1bor.tex"], 
           ["Tweedie, Richard L.", "tex_files/Tweedie%2C%20Richard%20L..tex"], 
           ["Tyler, David E.", "tex_files/Tyler%2C%20David%20E..tex"], 
           ["Utts, Jessica M.", "tex_files/Utts%2C%20Jessica%20M..tex"], 
           ["Vajda, Stefan", "tex_files/Vajda%2C%20Stefan.tex"], 
           ["Van Keilegom, Ingrid", "tex_files/Van%20Keilegom%2C%20Ingrid.tex"], 
           ["Van Ness, John W.", "tex_files/Van%20Ness%2C%20John%20W..tex"], 
           ["Van Ryzin, John R.", "tex_files/Van%20Ryzin%2C%20John%20R..tex"], 
           ["Vannucci, Marina", "tex_files/Vannucci%2C%20Marina.tex"], 
           ["Varadhan, S. R. Srinivasa", "tex_files/Varadhan%2C%20S.%20R.%20Srinivasa.tex"], 
           ["Vardi, Yehuda", "tex_files/Vardi%2C%20Yehuda.tex"], 
           ["Vares, Maria Eulália", "tex_files/Vares%2C%20Maria%20Eul%C3%A1lia.tex"], 
           ["Veinott, Arthur F., Jr.", "tex_files/Veinott%2C%20Arthur%20F.%2C%20Jr..tex"], 
           ["Vervaat, Wim", "tex_files/Vervaat%2C%20Wim.tex"], 
           ["Viens, Frederi G.", "tex_files/Viens%2C%20Frederi%20G..tex"], 
           ["Vitale, Richard A.", "tex_files/Vitale%2C%20Richard%20A..tex"], 
           ["Wahba, Grace", "tex_files/Wahba%2C%20Grace.tex"], 
           ["Wald, Abraham", "tex_files/Wald%2C%20Abraham.tex"], 
           ["Wallace, David L.", "tex_files/Wallace%2C%20David%20L..tex"], 
           ["Wallis, W. Allen", "tex_files/Wallis%2C%20W.%20Allen.tex"], 
           ["Wand, Matthew P.", "tex_files/Wand%2C%20Matthew%20P..tex"], 
           ["Wang, Jane-Ling", "tex_files/Wang%2C%20Jane-Ling.tex"], 
           ["Wang, Naisyin", "tex_files/Wang%2C%20Naisyin.tex"], 
           ["Wang, Suojin", "tex_files/Wang%2C%20Suojin.tex"], 
           ["Wang, Yazhen", "tex_files/Wang%2C%20Yazhen.tex"], 
           ["Wasserman, Larry A.", "tex_files/Wasserman%2C%20Larry%20A..tex"], 
           ["Waterman, Michael S.", "tex_files/Waterman%2C%20Michael%20S..tex"], 
           ["Watson, Geoffrey S.", "tex_files/Watson%2C%20Geoffrey%20S..tex"], 
           ["Watterson, Geoffrey A.", "tex_files/Watterson%2C%20Geoffrey%20A..tex"], 
           ["Waymire, Edward C.", "tex_files/Waymire%2C%20Edward%20C..tex"], 
           ["Wegman, Edward J.", "tex_files/Wegman%2C%20Edward%20J..tex"], 
           ["Wei, Ching-Zong", "tex_files/Wei%2C%20Ching-Zong.tex"], 
           ["Wei, Lee-Jen", "tex_files/Wei%2C%20Lee-Jen.tex"], 
           ["Weida, Frank M.", "tex_files/Weida%2C%20Frank%20M..tex"], 
           ["Weiss, Lionel I.", "tex_files/Weiss%2C%20Lionel%20I..tex"], 
           ["Wellner, Jon A.", "tex_files/Wellner%2C%20Jon%20A..tex"], 
           ["Wells, Martin T.", "tex_files/Wells%2C%20Martin%20T..tex"], 
           ["Welsch, Roy E.", "tex_files/Welsch%2C%20Roy%20E..tex"], 
           ["Welsh, Alan H.", "tex_files/Welsh%2C%20Alan%20H..tex"], 
           ["Wermuth, Nanny", "tex_files/Wermuth%2C%20Nanny.tex"], 
           ["West, Mike", "tex_files/West%2C%20Mike.tex"], 
           ["Wetherill, G. Barrie", "tex_files/Wetherill%2C%20G.%20Barrie.tex"], 
           ["Whittle, Peter", "tex_files/Whittle%2C%20Peter.tex"], 
           ["Wichura, Michael J.", "tex_files/Wichura%2C%20Michael%20J..tex"], 
           ["Wierman, John C.", "tex_files/Wierman%2C%20John%20C..tex"], 
           ["Wijsman, Robert A.", "tex_files/Wijsman%2C%20Robert%20A..tex"], 
           ["Wilk, Martin B.", "tex_files/Wilk%2C%20Martin%20B..tex"], 
           ["Wilkinson, Roger I.", "tex_files/Wilkinson%2C%20Roger%20I..tex"], 
           ["Wilks, Samuel S.", "tex_files/Wilks%2C%20Samuel%20S..tex"], 
           ["Williams, Evan J.", "tex_files/Williams%2C%20Evan%20J..tex"], 
           ["Williams, Ruth J.", "tex_files/Williams%2C%20Ruth%20J..tex"], 
           ["Wilson, Susan R.", "tex_files/Wilson%2C%20Susan%20R..tex"], 
           ["Winsor, Charles P.", "tex_files/Winsor%2C%20Charles%20P..tex"], 
           ["Wishart, John", "tex_files/Wishart%2C%20John.tex"], 
           ["Witting, Hermann", "tex_files/Witting%2C%20Hermann.tex"], 
           ["Wold, Herman O. A.", "tex_files/Wold%2C%20Herman%20O.%20A..tex"], 
           ["Wolfe, Douglas A.", "tex_files/Wolfe%2C%20Douglas%20A..tex"], 
           ["Wolfowitz, Jacob", "tex_files/Wolfowitz%2C%20Jacob.tex"], 
           ["Wolpert, Robert L.", "tex_files/Wolpert%2C%20Robert%20L..tex"], 
           ["Wong, Weng Kee", "tex_files/Wong%2C%20Weng%20Kee.tex"], 
           ["Wong, Wing Hung", "tex_files/Wong%2C%20Wing%20Hung.tex"], 
           ["Woodbury, Max A.", "tex_files/Woodbury%2C%20Max%20A..tex"], 
           ["Woodroofe, Michael B.", "tex_files/Woodroofe%2C%20Michael%20B..tex"], 
           ["Woyczyński, Wojbor A.", "tex_files/Woyczy%C5%84ski%2C%20Wojbor%20A..tex"], 
           ["Wright, Farroll T.", "tex_files/Wright%2C%20Farroll%20T..tex"], 
           ["Wright, Sewall G.", "tex_files/Wright%2C%20Sewall%20G..tex"], 
           ["Wu, C. F. Jeff", "tex_files/Wu%2C%20C.%20F.%20Jeff.tex"], 
           ["Wynn, Henry P.", "tex_files/Wynn%2C%20Henry%20P..tex"], 
           ["Xiao, Yimin", "tex_files/Xiao%2C%20Yimin.tex"], 
           ["Yahav, Joseph A.", "tex_files/Yahav%2C%20Joseph%20A..tex"], 
           ["Yakovlev, Andrej Y.", "tex_files/Yakovlev%2C%20Andrej%20Y..tex"], 
           ["Yamamoto, Sumiyasu", "tex_files/Yamamoto%2C%20Sumiyasu.tex"], 
           ["Yan, Jia-An", "tex_files/Yan%2C%20Jia-An.tex"], 
           ["Yang, Grace Lo", "tex_files/Yang%2C%20Grace%20Lo.tex"], 
           ["Yang, Yuhong", "tex_files/Yang%2C%20Yuhong.tex"], 
           ["Yao, Qiwei", "tex_files/Yao%2C%20Qiwei.tex"], 
           ["Yao, Yi-Ching", "tex_files/Yao%2C%20Yi-Ching.tex"], 
           ["Yatracos, Yannis", "tex_files/Yatracos%2C%20Yannis.tex"], 
           ["Ying, Zhiliang", "tex_files/Ying%2C%20Zhiliang.tex"], 
           ["Ylvisaker, N. Donald", "tex_files/Ylvisaker%2C%20N.%20Donald.tex"], 
           ["Yohai, Victor J.", "tex_files/Yohai%2C%20Victor%20J..tex"], 
           ["Youden, William J.", "tex_files/Youden%2C%20William%20J..tex"], 
           ["Young, G. Alastair", "tex_files/Young%2C%20G.%20Alastair.tex"], 
           ["Yu, Bin", "tex_files/Yu%2C%20Bin.tex"], 
           ["Zabell, Sandy L.", "tex_files/Zabell%2C%20Sandy%20L..tex"], 
           ["Zacks, Shelemyahu", "tex_files/Zacks%2C%20Shelemyahu.tex"], 
           ["Zakai, Moshe", "tex_files/Zakai%2C%20Moshe.tex"], 
           ["Zeitouni, Ofer", "tex_files/Zeitouni%2C%20Ofer.tex"], 
           ["Zelen, Marvin", "tex_files/Zelen%2C%20Marvin.tex"], 
           ["Zeng, Donglin", "tex_files/Zeng%2C%20Donglin.tex"], 
           ["Zhang, Chunming", "tex_files/Zhang%2C%20Chunming.tex"], 
           ["Zhang, Cun-Hui", "tex_files/Zhang%2C%20Cun-Hui.tex"], 
           ["Zhang, Heping", "tex_files/Zhang%2C%20Heping.tex"], 
           ["Zhao, Hongyu", "tex_files/Zhao%2C%20Hongyu.tex"], 
           ["Zhu, Hongtu", "tex_files/Zhu%2C%20Hongtu.tex"], 
           ["Zhu, Lixing", "tex_files/Zhu%2C%20Lixing.tex"], 
           ["Zidek, James V.", "tex_files/Zidek%2C%20James%20V..tex"], 
           ["Zinn, Joel", "tex_files/Zinn%2C%20Joel.tex"], 
           ["Zubin, Joseph", "tex_files/Zubin%2C%20Joseph.tex"], 
           ["de Acosta, Alejandro D.", "tex_files/de%20Acosta%2C%20Alejandro%20D..tex"], 
           ["de Finetti, Bruno", "tex_files/de%20Finetti%2C%20Bruno.tex"], 
           ["de Haan, Laurens", "tex_files/de%20Haan%2C%20Laurens.tex"], 
           ["de Leeuw, Jan", "tex_files/de%20Leeuw%2C%20Jan.tex"], 
           ["de la Peña, Victor H.", "tex_files/de%20la%20Pe%C3%B1a%2C%20Victor%20H..tex"], 
           ["den Hollander, W. Th. Frank", "tex_files/den%20Hollander%2C%20W.%20Th.%20Frank.tex"], 
           ["van Dantzig, David", "tex_files/van%20Dantzig%2C%20David.tex"], 
           ["van Dyk, David A.", "tex_files/van%20Dyk%2C%20David%20A..tex"], 
           ["van Eeden, Constance", "tex_files/van%20Eeden%2C%20Constance.tex"], 
           ["van Zwet, Willem R.", "tex_files/van%20Zwet%2C%20Willem%20R..tex"], 
           ["van de Geer, Sara A.", "tex_files/van%20de%20Geer%2C%20Sara%20A..tex"], 
           ["van der Vaart, Aad W.", "tex_files/van%20der%20Vaart%2C%20Aad%20W..tex"], 
           ["van der Waerden, Bartel L.", "tex_files/van%20der%20Waerden%2C%20Bartel%20L..tex"], 
           ["von Mises, Richard E.", "tex_files/von%20Mises%2C%20Richard%20E..tex"], 
           ["von Neumann, John", "tex_files/von%20Neumann%2C%20John.tex"], 
           ["von Sachs, Rainer", "tex_files/von%20Sachs%2C%20Rainer.tex"], 
           ["Çinlar, Erhan", "tex_files/%C3%87inlar%2C%20Erhan.tex"]]

## ims_sources.py ends here

